from __future__ import annotations
import sys, pathlib, argparse, json, dataclasses, math, random, itertools, bounds, warnings, inspect
from dataclasses import dataclass, field
from pathlib import Path
from fractions import Fraction
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple
from sage.all import *
from search_common import *
from collections import Counter
from sympy import symbols, expand
from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
from tate import *
from search_lll import *
from sat import *
from picard import *
from automorph import *
from torsion import *
from nslattice import *
from yau import *
from bounds import *
from selmer import *
from stats import *
from consensus import *
from mobius import *
from sage.misc.verbose import set_verbose
from functools import partial
from search_lll.mumford.mumford_parallel import init_worker
from markov import *

# --- path bootstrap: allow running directly from markov/ subdir ---
# -----------------------------------------------------------------

# search7_genus2.sage
# This file was *autogenerated* from the file search7_genus2.sage
# application modules
load('tower.sage')
load('search7_genus2.sage')
# DEAR AI READING THIS:  RAISE ALL EXCEPTIONS
# DEAR AI READING THIS:  all imports are available

try:
    PROFILE = profile
except NameError:
    def profile(arg2):
        """Line profiler default."""
        return arg2
    PROFILE = profile

_RELATION_MATRIX_AVAILABLE = True
# ---------------------------------------------------------------------------
# Project symbol registry.
#
# Symbols loaded from tower.sage / search7_genus2.sage are exec'd into this
# dict rather than directly into globals().  This avoids the silent-loss
# problem where exec(preparse(src), globals()) can drop symbols that are
# defined inside conditionals or local scopes in the sage file, and it gives
# resolve_project_symbol a stable lookup target that doesn't depend on the
# precise state of the module namespace at call time.
#
# For backward-compat, load_project_sources also copies everything into the
# module's real globals() so that sage-level `load()` idioms keep working.
# ---------------------------------------------------------------------------

"""genus2_markov_module.py

A self-contained Sage-based draft for the genus-2 fibration / Markov-walk idea.

Run under SageMath:
    sage -python genus2_markov_module.py --help

Design goals:
- keep the chain logic and divisor bookkeeping in one place
- optionally load companion project files (tower.sage, search7_genus2.sage)
- accept a fibration-step factory from your existing code
- recover candidate x_j values from the m-root equation
- recover x_k from a degree-5 intersection polynomial via Vieta when available
- support a simple Metropolis-style bias and restart-on-dead-end behavior

This is a draft module, not a proof that the attack works.
"""

StepFactory = Callable[..., Dict[str, Any]]
ScoreFn = Callable[[Any, Dict[str, Any]], float]

# ---------------------------------------------------------------------------
# Optional project bootstrap
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Core walker
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Convenience helpers for direct use
# ---------------------------------------------------------------------------

def relation_string(xi, xj, xk, curve_degree: int = 5) -> str:
    """Divisor relation: xi has double tangency (triple root), xj and xk are simple.
    For a degree-d curve: (d-2)*xi + xj + xk - d*∞ = 0.
    """
    mult = curve_degree - 2
    return f"{mult}*{xi} + {xj} + {xk} - {curve_degree}*∞ = 0"

# ---------------------------------------------------------------------------
# Minimal CLI
# ---------------------------------------------------------------------------

def _parse_coeffs(text: str) -> List[Fraction]:
    # Accept comma-separated rationals/ints.
    parts = [p.strip() for p in text.split(",") if p.strip()]
    return [QQ(p) for p in parts]

def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Genus-2 fibration Markov-walk draft module")
    ap.add_argument("--coeffs", default=None, help="Descending coefficients for y^2=f(x), comma-separated")
    ap.add_argument("--x0", default=None, help="Starting x-coordinate")
    ap.add_argument("--y0", default=None, help="Optional starting y-coordinate")
    ap.add_argument("--p", type=int, default=None, help="Finite-field prime p (omit for QQ)")
    ap.add_argument("--steps", type=int, default=10, help="Number of Markov steps")
    ap.add_argument("--seed", type=int, default=0, help="RNG seed")
    ap.add_argument("--log-jsonl", default=None, help="Write one JSON record per step to this file")
    ap.add_argument("--log-full-candidates", action="store_true", help="Write the full candidate pool to the JSONL log")
    ap.add_argument("--no-load", action="store_true", help="Do not load tower.sage/search7_genus2.sage")
    ap.add_argument("--max-n", type=int, default=80, help="Maximum n used to build 1D search vectors")
    ap.add_argument("--num-subsets", type=int, default=None, help="Prime-subset budget for the lattice search")
    ap.add_argument("--num-workers", type=int, default=None, help="Worker count for search subprocesses")
    args = ap.parse_args(argv)

    if not args.no_load:
        load_project_sources(verbose=True)

    coeffs = args.coeffs
    if coeffs is None:
        coeffs = resolve_project_symbol('COEFFS_GENUS2', required=True)
    else:
        coeffs = [QQ(c) for c in args.coeffs.split(',') if c.strip()]

    p = args.p if args.p is not None else resolve_project_symbol('FINITE_FIELD', default=None)

    x0 = args.x0
    if x0 is None:
        data_pts = resolve_project_symbol('DATA_PTS_GENUS2', required=True)
        if not data_pts:
            raise RuntimeError('No --x0 given and DATA_PTS_GENUS2 is empty')
        x0 = data_pts[0]
    x0 = GF(int(p))(x0) if p is not None else QQ(x0)

    y0 = args.y0
    if y0 is not None:
        y0 = GF(int(p))(y0) if p is not None else QQ(y0)
    else:
        yfun = resolve_project_symbol('get_y_unshifted_genus2', default=None)
        if yfun is not None:
            try:
                y0 = yfun(x0)
            except Exception:
                y0 = None
                raise

    base_points = project_base_points_from_globals(current_x=x0, current_y=y0, p=p)

    prime_pool = resolve_project_symbol('PRIME_POOL', required=True)
    num_subsets = args.num_subsets
    num_workers = args.num_workers if args.num_workers is not None else int(resolve_project_symbol('NUM_WORKERS', default=1))

    # Build a persistent pool once
    ctx = multiprocessing.get_context("spawn")  # safe for Sage / heavy objects
    pool = ctx.Pool(processes=num_workers, initializer=init_worker)  # adjust num processes
    chunk_size = 2 # how many multiples of the section to search per chunk

    search_fn = make_project_markov_search_fn(
        coeffs_genus2=coeffs,
        base_points=base_points,
        p=p,
        prime_pool=prime_pool,
        num_subsets=num_subsets,
        num_workers=num_workers,
        debug=False,
        max_n=args.max_n,
        precomputed_residues=None,
        all_found_x=set(), pool=pool, chunk_size=chunk_size
    )

    enable_step_diagnostics(Genus2MetropolisWalker)
    walker = build_default_walker(
        coeffs=coeffs,
        initial_x=x0,
        p=p,
        initial_y=y0,
        base_points=base_points,
        seed=args.seed,
        load_sources=False,
        verbose=True,
        search_fn=search_fn,
        log_path=args.log_jsonl,
        log_full_candidates=args.log_full_candidates,
    )
    results = walker.run(args.steps)
    # When done, clean up the pool
    pool.close()
    pool.join()

    walker.close_under_involution()
    # Live hits were already printed during the run (verbose=True)
    walker.cantor_summary()

    # Post-hoc queries
    # To inspect a specific atom from the walk:
    if walker.history:
        some_atom = walker.history[0].xi
        print("equiv partners of first xi:", walker.cantor_cache.equiv_partners(some_atom))
        print("can substitute?", walker.cantor_cache.can_substitute(some_atom))

    print_mixing_report(walker)

    _P = 2**31 - 1
    mat, atoms, used = walker.relation_matrix(include_step_leaves=False)
    print(f"[matrix] shape = {mat.nrows()} x {mat.ncols()}")
    print(f"[matrix] rank  = {mat.change_ring(_GF(_P)).rank()}  (mod {_P})")

    mat_walk_only, atoms_walk_only, _ = build_relation_matrix2(
        [r for r in walker.history if r.n >= 0],
        curve_degree=5,
        include_step_leaves=False,
    )
    print(f"walk-only rank: {mat_walk_only.change_ring(_GF(_P)).rank()} "
        f"shape: {mat_walk_only.nrows()}x{mat_walk_only.ncols()}  (mod {_P})")

    pruned_mat, pruned_atoms, removed = prune_dest_only(mat_walk_only, atoms_walk_only)
    print(f"[nullity] pruned {len(removed)} dest-only atoms, {len(pruned_atoms)} atoms remain")
    print_nullity_report(pruned_mat, pruned_atoms)

    print(walker.summary())
    # print_relation_matrix_summary omitted: recomputes rank internally (third change_ring)

    return 0 # for the memez

def _run_markov_mumford_search_for_point(
    *,
    cd,
    current_sections,
    prime_pool,
    vecs,
    rhs_list,
    shift,
    rationality_test_func,
    coeffs_genus2,
    tower_data,
    num_workers,
    debug=False,
    x_b=None,
    shifted_coeffs=None,
    pool=None, chunk_size=8
):
    """Call the legacy Mumford search and normalize the result for Markov use.

    The important thing here is to keep the raw payload available, because the
    smarter chooser wants provenance such as which n/vector produced each xj.
    """
    raw = run_mumford_search(
        cd, current_sections, prime_pool, vecs, rhs_list, shift,
        rationality_test_func, coeffs_genus2, tower_data,
        num_workers, debug, x_b, shifted_coeffs, markov_mode=True, pool=pool, chunk_size=chunk_size
    )
    return _normalize_markov_mumford_result(raw)

def _as_set(values):
    if values is None:
        return set()
    if isinstance(values, set):
        return set(values)
    if isinstance(values, (list, tuple)):
        return {v for v in values if v is not None}
    return {values}

def _dedupe_preserve_order(values):
    seen = set()
    out_vals = []
    for v in values:
        if v is None:
            continue
        try:
            key = v if hash(v) is not None else repr(v)
        except Exception:
            key = repr(v)
            raise
        if key in seen:
            continue
        seen.add(key)
        out_vals.append(v)
    return out_vals

def _candidate_x_from_obj(obj):
    if obj is None:
        return None
    if isinstance(obj, dict):
        for key in ("xj", "x", "x_val", "xcoord", "candidate_x", "x_value"):
            if key in obj and obj[key] is not None:
                return obj[key]
    return obj if not isinstance(obj, (dict, list, tuple, set)) else None

def _candidate_record_from_x(x, source="mumford_residue", **extra):
    rec = {"xj": x, "source": source}
    rec.update(extra)
    return rec

def _candidates_from_residues(residues, p):
    """Extract candidate records from mumford_residues {p: {vtup: {(x_val, rhs_idx): sols}}}.

    Each solution is now (mumford_tuple, yj_sign, v0, v1, m_root, rhs_idx) as
    written by _solve_worker_wrapper.  The result dict is now keyed by
    (x_val, rhs_idx) so that xj-RHS and xk-RHS results for the same x_val are
    not conflated.

    rhs_idx=0  ->  x_val is xj (the forward RHS, present in both RLINEAR modes)
    rhs_idx=1  ->  x_val is xk (the xk RHS, present only in RLINEAR=False mode)

    We emit one candidate record per (x_val, rhs_idx, yj_sign) triple.
    m_root is stored on the record so enrich_candidates can call
    compute_xk_from_fiber without reconstructing m from xi-xj (which is only
    valid under RLINEAR=True).

    Returns a list of dicts with keys: xj, yj_sign, v0, v1, m, rhs_idx, source.
    """
    records = []
    seen = set()  # (x_val, rhs_idx, yj_sign) dedup

    pmap = residues.get(p, {})
    for vtup, xmap in pmap.items():
        if not isinstance(xmap, dict):
            continue
        for key_pair, sols in xmap.items():
            if not sols:
                continue

            # New key format is (x_val, rhs_idx); accept bare x_val for
            # backward compat with any cached results still in the old format.
            if isinstance(key_pair, tuple) and len(key_pair) == 2:
                x_val, rhs_idx = key_pair
            else:
                x_val = key_pair
                rhs_idx = 0

            # Take the first solution's sign (multiple solutions at the same
            # x_val should agree on yj_sign since v(xj) is deterministic).
            first = sols[0]
            if isinstance(first, (tuple, list)) and len(first) == 6:
                # Current format: (mumford_tuple, x_val_sign, v0, v1, m_root, rhs_idx)
                # x_val_sign is the sign for x_val: yj_sign when rhs_idx=0, yk_sign when rhs_idx=1.
                _mtup, x_val_sign, v0, v1, m_root, _rhs_idx = first
                # rhs_idx in the tuple should match the key; trust the key.
            elif isinstance(first, (tuple, list)) and len(first) == 4:
                # Legacy format (RLINEAR=True only, m not needed there):
                # (mumford_tuple, yj_sign, v0, v1)
                _mtup, x_val_sign, v0, v1 = first
                m_root = None
            else:
                raise AssertionError(
                    f"_candidates_from_residues: unexpected solution format "
                    f"type={type(first)!r} len={len(first)} for x_val={x_val!r}. "
                    f"Expected 6-tuple (mumford_tuple, x_val_sign, v0, v1, m_root, rhs_idx) "
                    f"or legacy 4-tuple (mumford_tuple, yj_sign, v0, v1). "
                    f"Update _solve_worker_wrapper in mumford_parallel.py to emit this format."
                )

            if x_val_sign not in (1, -1):
                raise AssertionError(
                    f"_candidates_from_residues: x_val_sign={x_val_sign!r} is not +-1 "
                    f"for x_val={x_val!r}, rhs_idx={rhs_idx}."
                )

            dedup_key = (int(x_val), int(rhs_idx), x_val_sign)
            if dedup_key in seen:
                continue
            seen.add(dedup_key)

            # For rhs_idx=0: x_val is xj, x_val_sign is yj_sign.
            # For rhs_idx=1: x_val is xk, x_val_sign is yk_sign.
            # enrich_candidates will swap roles for rhs_idx=1 and recover the missing sign.
            records.append({
                "xj": None,             # Weierstrass x_val discarded; enrich_candidates reconstructs from m
                "yj_sign": x_val_sign,  # really yk_sign when rhs_idx=1; enrich_candidates corrects this
                "v0": v0,
                "v1": v1,
                "m": int(m_root) if m_root is not None else None,
                "rhs_idx": int(rhs_idx),
                "source": "mumford_residue",
            })

    return records

def _collect_mumford_candidate_x_values(obj, out=None):
    """
    Recursively collect candidate x-values from a Mumford payload.
    """
    if out is None:
        out = []

    if obj is None:
        return out

    if isinstance(obj, dict):
        for key in ("xj", "x", "x_val", "xcoord", "candidate_x", "x_value"):
            if key in obj and obj[key] is not None:
                out.append(obj[key])

        if obj and all(not isinstance(v, dict) for v in obj.values()):
            for k, v in obj.items():
                if isinstance(v, (list, tuple, set)) and not isinstance(k, (list, tuple, set, dict)):
                    out.append(k)

        for value in obj.values():
            _collect_mumford_candidate_x_values(value, out)
        return out

    if isinstance(obj, (list, tuple, set)):
        for value in obj:
            _collect_mumford_candidate_x_values(value, out)
        return out

    return out

def _normalize_markov_mumford_result(result, fallback_step=None):
    """
    Normalize the legacy Mumford-search return payload into a walker-friendly dict.
    """
    out = {
        "candidates": [],
        "candidate_records": [],
        "candidate_xs": set(),
        "new_sections": [],
        "precomputed_residues": None,
        "residues": None,          # markov_mode fast-exit: {p: {vtup: {x_val: [(sol, yj_sign, v0, v1)]}}}
        "stats": None,
        "raw_mumford_residues": None,
        "found_xs": set(),
    }

    if result is None:
        return out

    if isinstance(result, dict):
        out["raw_mumford_residues"] = result.get("raw_mumford_residues", result)
        out["precomputed_residues"] = result.get("precomputed_residues", None)
        out["residues"] = result.get("residues", None)   # signed residues from markov fast-exit
        out["stats"] = result.get("stats", None)
        out["new_sections"] = result.get("new_sections", [])

        for key in (
            "input_n", "vecs", "tower_context", "current_x", "current_y",
            "xi", "yi", "shift", "r_expr", "n_with_roots", "per_n_roots",
        ):
            if key in result:
                out[key] = result[key]

        if "found_xs" in result:
            out["found_xs"] = _as_set(result.get("found_xs"))
        if "candidate_xs" in result:
            out["candidate_xs"] = _as_set(result.get("candidate_xs"))

        raw_candidates = result.get("candidate_records", None)
        if raw_candidates is None:
            raw_candidates = result.get("candidates", None)

        if raw_candidates is not None:
            if isinstance(raw_candidates, (list, tuple)):
                out["candidate_records"] = list(raw_candidates)
            else:
                out["candidate_records"] = [raw_candidates]

        for cand in out["candidate_records"]:
            x = _candidate_x_from_obj(cand)
            if x is not None:
                out["candidate_xs"].add(x)
                out["found_xs"].add(x)

        if not out["candidate_xs"]:
            xs = _collect_mumford_candidate_x_values(out["raw_mumford_residues"], [])
            xs = _dedupe_preserve_order(xs)
            if xs:
                out["candidate_xs"] = set(xs)
                out["candidate_records"] = [_candidate_record_from_x(x) for x in xs]

        if not out["candidate_xs"] and fallback_step is not None:
            xs = _collect_mumford_candidate_x_values(fallback_step, [])
            xs = _dedupe_preserve_order(xs)
            if xs:
                out["candidate_xs"] = set(xs)
                out["candidate_records"] = [_candidate_record_from_x(x, source="fallback_step") for x in xs]

        if not out["candidate_records"] and out["candidate_xs"]:
            out["candidate_records"] = [_candidate_record_from_x(x) for x in out["candidate_xs"]]

        out["candidates"] = list(out["candidate_records"])

        try:
            out["candidate_counts"] = Counter(
                cand.get("xj")
                for cand in out["candidate_records"]
                if isinstance(cand, dict) and cand.get("xj") is not None
            )
        except Exception:
            out["candidate_counts"] = Counter()
            raise

        return out

    if isinstance(result, (tuple, list)):
        items = list(result)
        out["raw_mumford_residues"] = items

        xs = []
        found_xs = set()

        for item in items:
            if isinstance(item, (list, tuple, set)):
                for v in item:
                    if v is not None:
                        found_xs.add(v)
            xs.extend(_collect_mumford_candidate_x_values(item, []))

        xs = _dedupe_preserve_order(xs)

        if not xs and found_xs:
            xs = _dedupe_preserve_order(list(found_xs))

        out["found_xs"] = set(found_xs) if found_xs else set(xs)
        out["candidate_xs"] = set(xs)
        out["candidate_records"] = [{"xj": x, "source": "mumford_residue"} for x in xs]
        out["candidates"] = list(out["candidate_records"])

        for item in reversed(items):
            if isinstance(item, dict):
                if out["stats"] is None and "stats" in item:
                    out["stats"] = item["stats"]
                if out["precomputed_residues"] is None and "precomputed_residues" in item:
                    out["precomputed_residues"] = item["precomputed_residues"]
                if not out["new_sections"] and "new_sections" in item:
                    out["new_sections"] = item["new_sections"]

        try:
            out["candidate_counts"] = Counter(
                cand.get("xj")
                for cand in out["candidate_records"]
                if isinstance(cand, dict) and cand.get("xj") is not None
            )
        except Exception:
            out["candidate_counts"] = Counter()
            raise

        return out

    xs = _collect_mumford_candidate_x_values(result, [])
    xs = _dedupe_preserve_order(xs)
    out["raw_mumford_residues"] = result
    out["candidate_xs"] = set(xs)
    out["found_xs"] = set(xs)
    out["candidate_records"] = [{"xj": x, "source": "scalar_fallback"} for x in xs]
    out["candidates"] = list(out["candidate_records"])

    try:
        out["candidate_counts"] = Counter(xs)
    except Exception:
        out["candidate_counts"] = Counter()
        raise

    return out

def _normalize_candidate_output(result):
    """
    Normalize any search result into the walker-friendly dict shape.
    """
    if result is None:
        return {
            "candidates": [],
            "candidate_records": [],
            "candidate_xs": set(),
            "new_sections": [],
            "precomputed_residues": None,
            "stats": None,
        }

    if isinstance(result, dict):
        out = dict(result)
        out.setdefault("candidates", [])
        out.setdefault("candidate_records", out.get("candidates", []))
        out.setdefault("candidate_xs", set())
        out.setdefault("new_sections", [])
        out.setdefault("precomputed_residues", None)
        out.setdefault("stats", None)

        if not out.get("candidate_records") and out.get("candidates"):
            out["candidate_records"] = list(out["candidates"])

        if not out.get("candidate_xs"):
            xs = set()
            for cand in out.get("candidate_records", []):
                if isinstance(cand, dict):
                    x = cand.get("xj", None)
                    if x is None:
                        x = cand.get("x", None)
                    if x is None:
                        x = cand.get("candidate_x", None)
                    if x is None:
                        x = cand.get("x_value", None)
                    if x is not None:
                        xs.add(x)
                else:
                    if cand is not None:
                        xs.add(cand)
            out["candidate_xs"] = xs

        return out

    if isinstance(result, (tuple, list)) and len(result) == 4:
        a, b, c, d = result
        if isinstance(a, list) and a and isinstance(a[0], dict):
            xs = {cand.get("xj") for cand in a if cand.get("xj") is not None}
            return {
                "candidates": a,
                "candidate_records": a,
                "candidate_xs": xs,
                "new_sections": b,
                "precomputed_residues": c,
                "stats": d,
            }
        if isinstance(a, (set, list, tuple)):
            records = [{"xj": x} for x in a]
            return {
                "candidates": records,
                "candidate_records": records,
                "candidate_xs": set(a),
                "new_sections": b,
                "precomputed_residues": c,
                "stats": d,
            }

    raise TypeError(f"Unsupported search result type: {type(result)!r}")

def make_project_markov_search_fn(
    *,
    coeffs_genus2=None,
    base_points=None,
    p: Optional[int] = None,
    prime_pool=None,
    sconf=None,
    num_subsets: Optional[int] = None,
    num_workers: Optional[int] = None,
    debug: bool = False,
    max_n: int = 80,
    precomputed_residues=None,
    all_found_x=None, pool=None, chunk_size=8
):
    """Build a search function that rebuilds the tower for every current x."""
    coeffs_genus2 = coeffs_genus2 if coeffs_genus2 is not None else resolve_project_symbol('COEFFS_GENUS2', required=True)
    p = FINITE_FIELD
    prime_pool = PRIME_POOL
    num_workers = 20
    all_found_x = set()

    def search_fn(xi=None, current_x=None, n=None, seed=None, current_point=None, walker=None, **kwargs):
        if current_point is not None and isinstance(current_point, (tuple, list)) and len(current_point) >= 2:
            x_here, y_here = current_point[0], current_point[1]
        else:
            x_here = xi if xi is not None else current_x
            y_here = None
            if walker is not None and hasattr(walker, 'current_y'):
                y_here = walker.current_y
            if y_here is None:
                yfun = get_y_unshifted_genus2
                if yfun is not None:
                    y_here = yfun(x_here)

        ctx = build_project_tower_context_for_point(
            x_here,
            y_here,
            coeffs_genus2=coeffs_genus2,
            base_points=base_points if base_points is not None else getattr(walker, 'base_points', None),
            p=p,
            debug=debug,
        )

        assert ctx['search_rhs_list'] != ['INF'], ctx

        if debug:
            for k in ctx:
                print(k, ctx[k])

        n0 = int(n or 1)
        vecs = generate_ff_search_vectors(1)
        if not vecs:
            vecs = [tuple([n0])]

        raw = _run_markov_mumford_search_for_point(
            cd=ctx['cd'],
            current_sections=ctx['current_sections'],
            prime_pool=prime_pool,
            vecs=vecs,
            rhs_list=ctx['search_rhs_list'],
            shift=ctx['shift'],
            rationality_test_func=ctx['testfunc'],
            coeffs_genus2=coeffs_genus2,
            tower_data=ctx['tower_for_mumford'],
            num_workers=num_workers,
            debug=debug,
            x_b=None,
            shifted_coeffs=None, pool=pool, chunk_size=chunk_size
        )

        norm = _normalize_markov_mumford_result(raw, fallback_step=ctx)

        # Override candidate_records with sign-aware records extracted directly
        # from the raw residues dict, where each solution now carries yj_sign
        # and the v-polynomial coefficients needed to compute yk_sign.
        _raw_residues = norm.get('residues') if isinstance(norm, dict) else None
        if _raw_residues:
            sign_records = _candidates_from_residues(_raw_residues, p)
            if sign_records:
                norm['candidate_records'] = sign_records
                norm['candidates'] = sign_records
                norm['candidate_xs'] = {r['xj'] for r in sign_records}

        # Fertility: fraction of n-values (vecs) that had at least one F_p root across any prime.
        # precomputed_residues[p] is keyed only by v_tuples that had roots, so union of keys = fertile set.
        # We try two possible shapes: {prime: {vtup: solutions}} and the flat {vtup: solutions} fallback.
        _precomp = norm.get('precomputed_residues') or (raw.get('precomputed_residues') if isinstance(raw, dict) else None)
        if _precomp and vecs:
            fertile_vtups = set()
            per_n_root_counts: Dict[str, int] = {}  # vtup_str -> number of F_p roots for that n
            # Shape A: {prime: {vtup: solutions}}  (expected from markov_mode search)
            for p_entry in _precomp.values():
                if isinstance(p_entry, dict):
                    fertile_vtups.update(p_entry.keys())
                    for vtup, solutions in p_entry.items():
                        k = str(vtup)
                        if isinstance(solutions, (list, tuple, set)):
                            cnt = len(solutions)
                        elif solutions is not None:
                            cnt = 1
                        else:
                            cnt = 0
                        # Take max across primes (FF mode has 1 prime; guard for multi-prime callers)
                        if cnt > 0:
                            per_n_root_counts[k] = max(per_n_root_counts.get(k, 0), cnt)
            # Shape B: flat {vtup: solutions} — if Shape A found nothing
            if not fertile_vtups:
                for k, v in _precomp.items():
                    if not isinstance(v, dict):
                        fertile_vtups.add(k)
                        per_n_root_counts[str(k)] = 1
            norm['n_with_roots'] = len(per_n_root_counts)
            norm['n_total'] = len(vecs)
            norm['total_roots'] = sum(per_n_root_counts.values())
            norm['per_n_roots'] = per_n_root_counts  # {vtup_str: root_count}
        else:
            # Fallback filled in below, after enriched_candidates is assembled.
            norm['n_with_roots'] = None
            norm['n_total'] = len(vecs) if vecs else None
            norm['total_roots'] = None

        # Grab ingredients for xk computation.
        # f_i is in R_xm = PolynomialRing(Frac(GF(p)['m']), 'x') — poly in x with rational-function-in-m coefficients.
        # shifted_G_poly is the curve poly in x over GF(p).
        # At a specific m_val: evaluate each coeff of f_i at m=m_val -> univariate poly in x over GF(p).
        # Then G(x) - f_i(x, m_val) = 0 has roots xi(x3), xj, xk.
        _G_poly = ctx.get('shifted_G_poly')
        _tower = ctx.get('primary_tower')
        _fi = None
        if _tower and isinstance(_tower, (list, tuple)) and len(_tower) > 0:
            last = _tower[-1]
            if isinstance(last, dict):
                _fi = last.get('f_i')

        # Curve degree from project globals, defaulting to 5.
        _curve_degree = int(resolve_project_symbol('CURVE_DEGREE', default=5))

        # enrich_candidates handles: degenerate-xj skip, m recovery, xk computation
        # via compute_xk_from_fiber, yk_sign computation from v(xk), yj_sign/yk_sign
        # defaults, and xk_head injection with roles swapped.  It replaces the old
        # inline loop which computed xk but never computed yk_sign.
        enriched_candidates = enrich_candidates(
            norm,
            x_here=x_here,
            y_here=y_here,
            n0=n0,
            fi=_fi,
            G_poly=_G_poly,
            curve_degree=_curve_degree,
            p=p,
            shift=ctx.get('shift', 0),
            T=ctx.get('T'),
            T_inv=ctx.get('T_inv'),
        )

        # Attach S_of_m and inter_sym to every record while the tower context is
        # still available.  This is a fibration property of xi (not of any xj), so
        # we compute once and stamp it on all records.
        if _fi is not None and _G_poly is not None:
            _S_of_m_rec, _inter_sym_rec = compute_S_of_m(_fi, _G_poly, _curve_degree)
            for rec in enriched_candidates:
                if isinstance(rec, dict):
                    rec.setdefault('S_of_m', _S_of_m_rec)
                    rec.setdefault('inter_sym', _inter_sym_rec)
        # candidate_xs is the set of xj values derived from actual m-roots only.
        # xk_head records must be excluded here so the leaf-tracking in
        # _step_from_candidate_search can separate xj_set (m-root derived) from
        # xk_set (Vieta derived).  xk_head entries are still in enriched_candidates
        # and eligible for the Metropolis chooser.
        candidate_xs = {
            c.get('xj') for c in enriched_candidates
            if isinstance(c, dict)
            and c.get('xj') is not None
            and c.get('source') != 'xk_head'
        }

        # Dead-end reason classification — emitted into the result dict so the
        # walker can log *why* a step produced no candidates rather than silently
        # restarting.  Distinguishes failure modes:
        #   no_roots    — Mumford search found zero F_p roots for all vecs
        #   torsion     — roots found but all equal xi (xi is torsion / Weierstrass pt)
        #   ok          — candidates available
        # Note: all_inf_xk is no longer a reachable case — compute_xk_from_fiber now
        # raises AssertionError on a fiber pole rather than returning "∞".
        _dead_end_reason = 'ok'
        if not enriched_candidates:
            raw_candidate_records = norm.get('candidate_records', []) or []
            if not raw_candidate_records:
                _dead_end_reason = 'no_roots'
            else:
                xjs = [r.get('xj') for r in raw_candidate_records if isinstance(r, dict)]
                xjs_nondegenerate = [xj for xj in xjs if xj is not None and xj != x_here]
                if not xjs_nondegenerate:
                    _dead_end_reason = 'torsion'
                else:
                    _dead_end_reason = 'no_roots'  # shouldn't happen; fallback

        # Deferred fertility fallback: if precomputed_residues wasn't available, use
        # the m-root-derived candidate count as a lower-bound proxy.
        # Do NOT include xk_head records in this count — they are not m-roots.
        if norm.get('n_with_roots') is None and vecs:
            n_mroot_cands = sum(
                1 for c in enriched_candidates
                if isinstance(c, dict) and c.get('source') != 'xk_head'
            )
            if n_mroot_cands > 0:
                norm['n_with_roots'] = min(n_mroot_cands, len(vecs))
                norm['n_total'] = len(vecs)
                norm['total_roots'] = n_mroot_cands
                norm['per_n_roots'] = {}  # per-vec provenance not available without precomputed_residues

        n_xk_head = sum(1 for c in enriched_candidates
                        if isinstance(c, dict) and c.get('source') == 'xk_head')

        S_of_m_step, _ = compute_S_of_m(_fi, _G_poly, _curve_degree) if _fi is not None else (None, None)
        result = {
            'candidates': enriched_candidates,
            'candidate_records': enriched_candidates,
            'candidate_xs': candidate_xs,       # xj-only (m-root derived), for leaf tracking
            'n_xk_head': n_xk_head,             # how many xk_head alternatives were injected
            'stats': norm.get('stats', None),
            'found_xs': norm.get('found_xs', set()),
            'input_n': n0,
            'S_of_m': S_of_m_step,   # fibration property of this xi, not of any xj
            'fi': _fi,               # symbolic fiber poly in x over Frac(Fp[m]); needed for synthetic injection
            'G_poly': _G_poly,       # curve poly in x over Fp; needed for synthetic injection
            'vecs': vecs,
            'n_with_roots': norm.get('n_with_roots', None),
            'n_total': norm.get('n_total', None),
            'total_roots': norm.get('total_roots', None),
            'per_n_roots': norm.get('per_n_roots', None),
            'dead_end_reason': _dead_end_reason,
            # Memory Fix: Omit 'context', 'raw_mumford_residues', 'new_sections', 'precomputed_residues'
            # which hold uncollectable SageMath Rings and Ideals.
        }

        return result

    return search_fn

def poly_roots_with_multiplicity(poly) -> List[Tuple[Any, int]]:
    """Return roots as (root, multiplicity) pairs over the polynomial's base field."""
    roots = poly.roots(multiplicities=True)
    assert roots, roots
    return [(r, int(m)) for r, m in roots]

def safe_solve_univariate_roots(poly, ring=None) -> List[Any]:
    """Solve poly=0 in its base ring, returning roots if Sage can see them."""
    roots = poly.roots(multiplicities=False)
    assert roots, roots
    return list(roots)

def compute_fertility(norm, raw, vecs):
    precomp = norm.get('precomputed_residues') or (
        raw.get('precomputed_residues') if isinstance(raw, dict) else None
    )

    if not (precomp and vecs):
        return {
            'n_with_roots': None,
            'n_total': len(vecs) if vecs else None,
            'total_roots': None,
            'per_n_roots': None,
        }

    fertile = set()
    per_n = {}

    for entry in precomp.values():
        if isinstance(entry, dict):
            fertile.update(entry.keys())
            for vtup, sols in entry.items():
                k = str(vtup)
                cnt = len(sols) if isinstance(sols, (list, tuple, set)) else (1 if sols else 0)
                if cnt > 0:
                    per_n[k] = max(per_n.get(k, 0), cnt)

    if not fertile:
        for k, v in precomp.items():
            if not isinstance(v, dict):
                fertile.add(k)
                per_n[str(k)] = 1

    return {
        'n_with_roots': len(per_n),
        'n_total': len(vecs),
        'total_roots': sum(per_n.values()),
        'per_n_roots': per_n,
    }

def exec_namespace(src: str) -> Dict[str, Any]:
    """Execute preparsed sage source and return the resulting namespace."""
    ns: Dict[str, Any] = {}
    exec(src, ns)
    return ns

def load_project_sources(base_dir: Optional[Path] = None, verbose: bool = True) -> Dict[str, bool]:
    """Load tower.sage and search7_genus2.sage into PROJECT_REGISTRY."""
    here = Path(base_dir) if base_dir is not None else Path(__file__).resolve().parent
    loaded: Dict[str, bool] = {}
    for name in ("tower.sage", "search7_genus2.sage"):
        path = here / name
        if verbose:
            print(f"[bootstrap] loading {path}")
        try:
            with open(path, "r") as f:
                src = f.read()
        except FileNotFoundError:
            if verbose:
                print(f"[bootstrap] WARNING: {path} not found, skipping")
            loaded[name] = False
            raise

        src = src.replace("    main_genus2()", "    pass # main_genus2() disabled")

        # Mutate the shared dict in-place so walkerclass.resolve_project_symbol sees it
        PROJECT_REGISTRY.update(
            {k: v for k, v in exec_namespace(preparse(src)).items()
             if not k.startswith('__')}
        )
        globals().update({k: v for k, v in PROJECT_REGISTRY.items()
                          if not k.startswith('__')})
        loaded[name] = True

    return loaded

def enrich_candidates(
    norm,
    x_here,
    y_here,
    n0,
    fi,
    G_poly,
    curve_degree,
    p=None,
    shift=0,
    T=None,
    T_inv=None,
):
    enriched = []

    # If we don't have the fiber or curve, we can't do the pure geometric return path.
    # We bail early rather than silently returning garbage.
    if p is None or G_poly is None or fi is None:
        return []

    Fp = GF(int(p))
    shift_fp = Fp(shift)

    # Frame transformers
    def _to_fiber_frame(v):
        v_s = Fp(v) + shift_fp
        return T(v_s) if T is not None else v_s

    def _from_fiber_frame(v):
        v_t = T_inv(v) if T_inv is not None else v
        return v_t - shift_fp

    x_here_f = _to_fiber_frame(x_here)
    R_x = PolynomialRing(Fp, 'x')

    for cand in norm.get('candidate_records', []) or norm.get('candidates', []):
        rec = dict(cand) if isinstance(cand, dict) else {'xj': cand}

        # Step 1: Extract m. If we don't have m, the fiber recipe stops here.
        m_val = rec.get('m')
        if m_val is None:
            if RLINEAR and rec.get('xj') is not None:
                m_val = Fp(x_here) - Fp(rec['xj'])
            else:
                continue

        m_val_fp = Fp(m_val)

        # Step 2: Evaluate symbolic fiber polynomial fi(x, m) at m = m_val
        try:
            # fi is over Frac(Fp[m])[x]. We map coefficients to evaluate at m_val.
            f_eval_poly = R_x([c.subs(m=m_val_fp) for c in fi.list()])
        except ZeroDivisionError:
            continue # Pole in the fiber, skip

        # Step 3: Intersect fiber with curve: I(x) = G(x) - f(x)^2
        G_Rx = R_x(G_poly)
        intersection_poly = G_Rx - f_eval_poly**2

        # Step 4: Obtain ALL roots directly from the intersection
        roots_wm = intersection_poly.roots()

        other_roots_f = []
        actual_xi_mult = 0

        for r, mult in roots_wm:
            if r == x_here_f:
                actual_xi_mult += mult
                # Account for cases where xi has higher multiplicity (e.g., xi = xj)
                if mult > (curve_degree - 2):
                    other_roots_f.extend([r] * (mult - (curve_degree - 2)))
            else:
                other_roots_f.extend([r] * mult)

        # Step 5: soft FAIL on non-QR/Extension Field Roots
        # If we don't have exactly 2 other roots in Fp, they are in a quadratic extension field.
        # This explicitly fulfills the requirement to throw on non-quadratic residues.
        if len(other_roots_f) != 2:
            #print(
            #    f"Intersection failed to produce 2 base-field roots for m={m_val}. ",
            #    f"Roots found: {other_roots_f}. Non-Quadratic Residue encountered."
            #)
            continue

        xj_f, xk_f = other_roots_f[0], other_roots_f[1]

        # Step 6: Evaluate Y directly from the fiber (NO MUMFORD v(x) USED)
        yj_f = f_eval_poly(xj_f)
        yk_f = f_eval_poly(xk_f)

        # Step 7: HARD FAIL on Curve mismatch & Assign Canonical Signs
        def _get_strict_sign(x_val_f, y_val_f):
            y_int = int(y_val_f)
            curve_y2 = int(G_poly(x_val_f))

            # If the fiber's Y squared doesn't match the curve's G(X), something is severely broken.
            if (y_int**2) % int(p) != curve_y2:
                raise ValueError(
                    f"Y-coordinate validation failed! Fiber gave Y={y_val_f}, "
                    f"but Y^2 != G(X) for X={x_val_f}."
                )

            canonical_y = min(y_int, int(p) - y_int)
            return 1 if y_int == canonical_y else -1

        yj_sign = _get_strict_sign(xj_f, yj_f)
        yk_sign = _get_strict_sign(xk_f, yk_f)

        # Step 8: Transform back to affine Weierstrass coords
        xj_val = _from_fiber_frame(xj_f)
        xk_val = _from_fiber_frame(xk_f)

        # Step 9: Pack the purely geometric enriched record
        new_rec = {
            'xi': x_here,
            'yi': y_here,
            'xj': xj_val,
            'xk': xk_val,
            'yj_sign': yj_sign,
            'yk_sign': yk_sign,
            'm': m_val,
            'input_n': n0,
            'source': 'pure_fiber_intersection',
            'xi_mult': actual_xi_mult,
            'intersection_poly': intersection_poly,
            'shift': shift
        }

        enriched.append(new_rec)

        # Inject xk-head if RLINEAR (swapping roles for the walker)
        if RLINEAR and xk_val != x_here:
            enriched.append({
                'xi': x_here,
                'yi': y_here,
                'xj': xk_val,
                'xk': xj_val,
                'yj_sign': yk_sign, # Swap signs
                'yk_sign': yj_sign, # Swap signs
                'm': Fp(x_here) - Fp(xk_val),
                'input_n': n0,
                'source': 'xk_head',
                'xi_mult': actual_xi_mult,
                'shift': shift
            })

    return enriched

if __name__ == "__main__":
    raise SystemExit(main())
