from __future__ import annotations
import sys, pathlib, argparse, json, dataclasses, math, random, itertools, bounds, warnings, inspect
from dataclasses import dataclass, field
from pathlib import Path
from fractions import Fraction
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple
from sage.all import *
from search_common import *
from collections import Counter
from sympy import symbols, expand
from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
from tate import *
from search_lll import *
from sat import *
from picard import *
from automorph import *
from torsion import *
from nslattice import *
from yau import *
from bounds import *
from selmer import *
from stats import *
from consensus import *
from mobius import *
from sage.misc.verbose import set_verbose
from functools import partial
from search_lll.mumford.mumford_parallel import init_worker
from markov import *

try:
    from mumford_oscar_bridge import mumford_precompute_residues_oscar as _oscar_residues
    _OSCAR_AVAILABLE = True
except ImportError:
    _OSCAR_AVAILABLE = False

# --- Global Registry ---
PROJECT_REGISTRY: Dict[str, Any] = {}
# -----------------------
# --- path bootstrap: allow running directly from markov/ subdir ---
# -----------------------------------------------------------------

# search7_genus2.sage
# This file was *autogenerated* from the file search7_genus2.sage
# application modules
# DEAR AI READING THIS:  RAISE ALL EXCEPTIONS!!!!!
# DEAR AI READING THIS:  all imports are available

try:
    PROFILE = profile
except NameError:
    def profile(arg2):
        """Line profiler default."""
        return arg2
    PROFILE = profile

_RELATION_MATRIX_AVAILABLE = True
# ---------------------------------------------------------------------------
# Project symbol registry.
#
# Symbols loaded from tower.sage / search7_genus2.sage are exec'd into this
# dict rather than directly into globals().  This avoids the silent-loss
# problem where exec(preparse(src), globals()) can drop symbols that are
# defined inside conditionals or local scopes in the sage file, and it gives
# resolve_project_symbol a stable lookup target that doesn't depend on the
# precise state of the module namespace at call time.
#
# For backward-compat, load_project_sources also copies everything into the
# module's real globals() so that sage-level `load()` idioms keep working.
# ---------------------------------------------------------------------------

"""genus2_markov_module.py

A self-contained Sage-based draft for the genus-2 fibration / Markov-walk idea.

Run under SageMath:
    sage -python genus2_markov_module.py --help

Design goals:
- keep the chain logic and divisor bookkeeping in one place
- optionally load companion project files (tower.sage, search7_genus2.sage)
- accept a fibration-step factory from your existing code
- recover candidate x_j values from the m-root equation
- recover x_k from a degree-5 intersection polynomial via Vieta when available
- support a simple Metropolis-style bias and restart-on-dead-end behavior

This is a draft module, not a proof that the attack works.
"""

StepFactory = Callable[..., Dict[str, Any]]
ScoreFn = Callable[[Any, Dict[str, Any]], float]

# ---------------------------------------------------------------------------
# Optional project bootstrap
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Core walker
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Convenience helpers for direct use
# ---------------------------------------------------------------------------

def relation_string(xi, xj, xk, curve_degree: int = 5) -> str:
    """Divisor relation: xi has double tangency (triple root), xj and xk are simple.
    For a degree-d curve: (d-2)*xi + xj + xk - d*∞ = 0.
    """
    mult = curve_degree - 2
    return f"{mult}*{xi} + {xj} + {xk} - {curve_degree}*∞ = 0"

# ---------------------------------------------------------------------------
# Minimal CLI
# ---------------------------------------------------------------------------

def _parse_coeffs(text: str) -> List[Fraction]:
    # Accept comma-separated rationals/ints.
    parts = [p.strip() for p in text.split(",") if p.strip()]
    return [QQ(p) for p in parts]

def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Genus-2 fibration Markov-walk draft module")
    ap.add_argument("--coeffs", default=None, help="Descending coefficients for y^2=f(x), comma-separated")
    ap.add_argument("--x0", default=None, help="Starting x-coordinate")
    ap.add_argument("--y0", default=None, help="Optional starting y-coordinate")
    ap.add_argument("--p", type=int, default=None, help="Finite-field prime p (omit for QQ)")
    ap.add_argument("--steps", type=int, default=10, help="Number of Markov steps")
    ap.add_argument("--seed", type=int, default=0, help="RNG seed")
    ap.add_argument("--log-jsonl", default=None, help="Write one JSON record per step to this file")
    ap.add_argument("--log-full-candidates", action="store_true", help="Write the full candidate pool to the JSONL log")
    ap.add_argument("--no-load", action="store_true", help="Do not load tower.sage/search7_genus2.sage")
    ap.add_argument("--max-n", type=int, default=80, help="Maximum n used to build 1D search vectors")
    ap.add_argument("--num-subsets", type=int, default=None, help="Prime-subset budget for the lattice search")
    ap.add_argument("--num-workers", type=int, default=None, help="Worker count for search subprocesses")
    args = ap.parse_args(argv)

    if not args.no_load:
        load_project_sources(verbose=True)

    coeffs = args.coeffs
    if coeffs is None:
        coeffs = resolve_project_symbol('COEFFS_GENUS2', required=True)
    else:
        coeffs = [QQ(c) for c in args.coeffs.split(',') if c.strip()]

    p = args.p if args.p is not None else resolve_project_symbol('FINITE_FIELD', default=None)

    x0 = args.x0
    if x0 is None:
        data_pts = resolve_project_symbol('DATA_PTS_GENUS2', required=True)
        if not data_pts:
            raise RuntimeError('No --x0 given and DATA_PTS_GENUS2 is empty')
        x0 = data_pts[0]
    x0 = GF(int(p))(x0) if p is not None else QQ(x0)

    y0 = args.y0
    if y0 is not None:
        y0 = GF(int(p))(y0) if p is not None else QQ(y0)
    else:
        yfun = resolve_project_symbol('get_y_unshifted_genus2', default=None)
        if yfun is not None:
            try:
                y0 = yfun(x0)
            except Exception:
                y0 = None
                raise

    base_points = project_base_points_from_globals(current_x=x0, current_y=y0, p=p)

    prime_pool = resolve_project_symbol('PRIME_POOL', required=True)
    num_subsets = args.num_subsets
    num_workers = args.num_workers if args.num_workers is not None else int(resolve_project_symbol('NUM_WORKERS', default=1))

    # Build a persistent pool once
    ctx = multiprocessing.get_context("spawn")  # safe for Sage / heavy objects
    pool = ctx.Pool(processes=num_workers, initializer=init_worker)  # adjust num processes
    chunk_size = 2 # how many multiples of the section to search per chunk

    search_fn = make_project_markov_search_fn(
        coeffs_genus2=coeffs,
        base_points=base_points,
        p=p,
        prime_pool=prime_pool,
        num_subsets=num_subsets,
        num_workers=num_workers,
        debug=False,
        max_n=args.max_n,
        precomputed_residues=None,
        all_found_x=set(), pool=pool, chunk_size=chunk_size
    )

    enable_step_diagnostics(Genus2MetropolisWalker)
    walker = build_default_walker(
        coeffs=coeffs,
        initial_x=x0,
        p=p,
        initial_y=y0,
        base_points=base_points,
        seed=args.seed,
        load_sources=False,
        verbose=True,
        search_fn=search_fn,
        log_path=args.log_jsonl,
        log_full_candidates=args.log_full_candidates,
    )
    results = walker.run(args.steps)
    # When done, clean up the pool
    pool.close()
    pool.join()

    walker.close_under_involution()
    # Live hits were already printed during the run (verbose=True)
    walker.cantor_summary()

    # Post-hoc queries
    # To inspect a specific atom from the walk:
    if walker.history:
        some_atom = walker.history[0].xi
        print("equiv partners of first xi:", walker.cantor_cache.equiv_partners(some_atom))
        print("can substitute?", walker.cantor_cache.can_substitute(some_atom))

    print_mixing_report(walker)

    _P = 2**31 - 1
    mat, atoms, used = walker.relation_matrix(include_step_leaves=False)
    print(f"[matrix] shape = {mat.nrows()} x {mat.ncols()}")
    print(f"[matrix] rank  = {mat.change_ring(_GF(_P)).rank()}  (mod {_P})")

    mat_walk_only, atoms_walk_only, _ = build_relation_matrix2(
        [r for r in walker.history if r.n >= 0],
        curve_degree=5,
        include_step_leaves=False,
    )
    print(f"walk-only rank: {mat_walk_only.change_ring(_GF(_P)).rank()} "
        f"shape: {mat_walk_only.nrows()}x{mat_walk_only.ncols()}  (mod {_P})")

    pruned_mat, pruned_atoms, removed = prune_dest_only(mat_walk_only, atoms_walk_only)
    print(f"[nullity] pruned {len(removed)} dest-only atoms, {len(pruned_atoms)} atoms remain")
    print_nullity_report(pruned_mat, pruned_atoms)

    print(walker.summary())
    # print_relation_matrix_summary omitted: recomputes rank internally (third change_ring)

    return 0 # for the memez



if __name__ == "__main__":
    raise SystemExit(main())
