from __future__ import annotations
import argparse, json, dataclasses, math, random, itertools, bounds, warnings, sys, inspect
from dataclasses import dataclass, field
from pathlib import Path
from fractions import Fraction
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple
from sage.all import *
from search_common import *
from collections import Counter
from sympy import symbols, expand
from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
from tate import *
from search_lll import *
from sat import *
from picard import *
from automorph import *
from torsion import *
from nslattice import *
from yau import *
from bounds import *
from selmer import *
from stats import *
from consensus import *
from mobius import *
from sage.misc.verbose import set_verbose
from relation_matrix import *
from functools import partial
from walkerclass import *
from search_lll.mumford.mumford_parallel import init_worker

# search7_genus2.sage
# This file was *autogenerated* from the file search7_genus2.sage
# application modules
load('tower.sage')
load('search7_genus2.sage')
# DEAR AI READING THIS:  RAISE ALL EXCEPTIONS
# DEAR AI READING THIS:  all imports are available

try:
    PROFILE = profile
except NameError:
    def profile(arg2):
        """Line profiler default."""
        return arg2
    PROFILE = profile

_RELATION_MATRIX_AVAILABLE = True
# ---------------------------------------------------------------------------
# Project symbol registry.
#
# Symbols loaded from tower.sage / search7_genus2.sage are exec'd into this
# dict rather than directly into globals().  This avoids the silent-loss
# problem where exec(preparse(src), globals()) can drop symbols that are
# defined inside conditionals or local scopes in the sage file, and it gives
# resolve_project_symbol a stable lookup target that doesn't depend on the
# precise state of the module namespace at call time.
#
# For backward-compat, load_project_sources also copies everything into the
# module's real globals() so that sage-level `load()` idioms keep working.
# ---------------------------------------------------------------------------

"""genus2_markov_module.py

A self-contained Sage-based draft for the genus-2 fibration / Markov-walk idea.

Run under SageMath:
    sage -python genus2_markov_module.py --help

Design goals:
- keep the chain logic and divisor bookkeeping in one place
- optionally load companion project files (tower.sage, search7_genus2.sage)
- accept a fibration-step factory from your existing code
- recover candidate x_j values from the m-root equation
- recover x_k from a degree-5 intersection polynomial via Vieta when available
- support a simple Metropolis-style bias and restart-on-dead-end behavior

This is a draft module, not a proof that the attack works.
"""

StepFactory = Callable[..., Dict[str, Any]]
ScoreFn = Callable[[Any, Dict[str, Any]], float]

# ---------------------------------------------------------------------------
# Optional project bootstrap
# ---------------------------------------------------------------------------

def load_project_sources(base_dir: Optional[Path] = None, verbose: bool = True) -> Dict[str, bool]:
    """Load tower.sage and search7_genus2.sage into PROJECT_REGISTRY.

    Symbols are exec'd into the registry dict first (atomic, stable lookup),
    then pushed into the module's real globals() for backward compat with any
    code that references them by name at module level.  The two-stage approach
    avoids the silent-loss problem where exec(preparse(src), globals()) can
    drop symbols defined inside sage-level conditionals or local scopes.
    """
    global PROJECT_REGISTRY
    here = Path(base_dir) if base_dir is not None else Path(__file__).resolve().parent
    loaded: Dict[str, bool] = {}
    for name in ("tower.sage", "search7_genus2.sage"):
        path = here / name
        if verbose:
            print(f"[bootstrap] loading {path}")
        try:
            with open(path, "r") as f:
                src = f.read()
        except FileNotFoundError:
            if verbose:
                print(f"[bootstrap] WARNING: {path} not found, skipping")
            loaded[name] = False
            raise
            continue

        # Suppress accidental top-level main() invocations.
        src = src.replace("    main_genus2()", "    pass # main_genus2() disabled")

        # Execute into registry first.
        exec(preparse(src), PROJECT_REGISTRY)
        # Push into module globals for any code using direct name references.
        globals().update({k: v for k, v in PROJECT_REGISTRY.items()
                          if not k.startswith('__')})
        loaded[name] = True

    return loaded

# ---------------------------------------------------------------------------
# Core walker
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Convenience helpers for direct use
# ---------------------------------------------------------------------------

def relation_string(xi, xj, xk, curve_degree: int = 5) -> str:
    """Divisor relation: xi has double tangency (triple root), xj and xk are simple.
    For a degree-d curve: (d-2)*xi + xj + xk - d*∞ = 0.
    """
    mult = curve_degree - 2
    return f"{mult}*{xi} + {xj} + {xk} - {curve_degree}*∞ = 0"

# ---------------------------------------------------------------------------
# Minimal CLI
# ---------------------------------------------------------------------------

def _parse_coeffs(text: str) -> List[Fraction]:
    # Accept comma-separated rationals/ints.
    parts = [p.strip() for p in text.split(",") if p.strip()]
    return [QQ(p) for p in parts]

def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Genus-2 fibration Markov-walk draft module")
    ap.add_argument("--coeffs", default=None, help="Descending coefficients for y^2=f(x), comma-separated")
    ap.add_argument("--x0", default=None, help="Starting x-coordinate")
    ap.add_argument("--y0", default=None, help="Optional starting y-coordinate")
    ap.add_argument("--p", type=int, default=None, help="Finite-field prime p (omit for QQ)")
    ap.add_argument("--steps", type=int, default=10, help="Number of Markov steps")
    ap.add_argument("--seed", type=int, default=0, help="RNG seed")
    ap.add_argument("--log-jsonl", default=None, help="Write one JSON record per step to this file")
    ap.add_argument("--log-full-candidates", action="store_true", help="Write the full candidate pool to the JSONL log")
    ap.add_argument("--no-load", action="store_true", help="Do not load tower.sage/search7_genus2.sage")
    ap.add_argument("--max-n", type=int, default=80, help="Maximum n used to build 1D search vectors")
    ap.add_argument("--num-subsets", type=int, default=None, help="Prime-subset budget for the lattice search")
    ap.add_argument("--num-workers", type=int, default=None, help="Worker count for search subprocesses")
    args = ap.parse_args(argv)

    if not args.no_load:
        load_project_sources(verbose=True)

    coeffs = args.coeffs
    if coeffs is None:
        coeffs = resolve_project_symbol('COEFFS_GENUS2', required=True)
    else:
        coeffs = [QQ(c) for c in args.coeffs.split(',') if c.strip()]

    p = args.p if args.p is not None else resolve_project_symbol('FINITE_FIELD', default=None)

    x0 = args.x0
    if x0 is None:
        data_pts = resolve_project_symbol('DATA_PTS_GENUS2', required=True)
        if not data_pts:
            raise RuntimeError('No --x0 given and DATA_PTS_GENUS2 is empty')
        x0 = data_pts[0]
    x0 = GF(int(p))(x0) if p is not None else QQ(x0)

    y0 = args.y0
    if y0 is not None:
        y0 = GF(int(p))(y0) if p is not None else QQ(y0)
    else:
        yfun = resolve_project_symbol('get_y_unshifted_genus2', default=None)
        if yfun is not None:
            try:
                y0 = yfun(x0)
            except Exception:
                y0 = None
                raise

    base_points = project_base_points_from_globals(current_x=x0, current_y=y0, p=p)

    prime_pool = resolve_project_symbol('PRIME_POOL', required=True)
    num_subsets = args.num_subsets
    num_workers = args.num_workers if args.num_workers is not None else int(resolve_project_symbol('NUM_WORKERS', default=1))

    # Build a persistent pool once
    ctx = multiprocessing.get_context("spawn")  # safe for Sage / heavy objects
    pool = ctx.Pool(processes=16, initializer=init_worker)  # adjust num processes
    chunk_size = 8 # how many multiples of the section to search per chunk

    search_fn = make_project_markov_search_fn(
        coeffs_genus2=coeffs,
        base_points=base_points,
        p=p,
        prime_pool=prime_pool,
        num_subsets=num_subsets,
        num_workers=num_workers,
        debug=False,
        max_n=args.max_n,
        precomputed_residues=None,
        all_found_x=set(), pool=pool, chunk_size=chunk_size
    )

    enable_step_diagnostics(Genus2MetropolisWalker)
    walker = build_default_walker(
        coeffs=coeffs,
        initial_x=x0,
        p=p,
        initial_y=y0,
        base_points=base_points,
        seed=args.seed,
        load_sources=False,
        verbose=True,
        search_fn=search_fn,
        log_path=args.log_jsonl,
        log_full_candidates=args.log_full_candidates,
    )
    results = walker.run(args.steps)
    # When done, clean up the pool
    pool.close()
    pool.join()

    walker.close_under_involution()
    # Live hits were already printed during the run (verbose=True)
    walker.cantor_summary()

    # Post-hoc queries
    # To inspect a specific atom from the walk:
    if walker.history:
        some_atom = walker.history[0].xi
        print("equiv partners of first xi:", walker.cantor_cache.equiv_partners(some_atom))
        print("can substitute?", walker.cantor_cache.can_substitute(some_atom))

    mat, atoms, used = walker.relation_matrix()
    print(f"[matrix] shape = {mat.nrows()} x {mat.ncols()}")
    print(f"[matrix] rank  = {mat.rank()}")

    mat_walk_only, _, _ = build_relation_matrix2(
        [r for r in walker.history if r.n >= 0],  # n=-1 are free/involution records
        curve_degree=5
    )
    print(f"walk-only rank: {mat_walk_only.rank()} shape: {mat_walk_only.nrows()}x{mat_walk_only.ncols()}")

    print(walker.summary())

    # NEW: actually compute and print matrix rank
    try:
        walker.print_relation_summary()
    except Exception as e:
        print(f"[matrix] failed: {e}")
        raise

    return 0 # for the memez

def _run_markov_mumford_search_for_point(
    *,
    cd,
    current_sections,
    prime_pool,
    vecs,
    rhs_list,
    shift,
    rationality_test_func,
    coeffs_genus2,
    tower_data,
    num_workers,
    debug=False,
    x_b=None,
    shifted_coeffs=None,
    pool=None, chunk_size=8
):
    """Call the legacy Mumford search and normalize the result for Markov use.

    The important thing here is to keep the raw payload available, because the
    smarter chooser wants provenance such as which n/vector produced each xj.
    """
    raw = run_mumford_search(
        cd, current_sections, prime_pool, vecs, rhs_list, shift,
        rationality_test_func, coeffs_genus2, tower_data,
        num_workers, debug, x_b, shifted_coeffs, markov_mode=True, pool=pool, chunk_size=chunk_size
    )
    return _normalize_markov_mumford_result(raw)

def _as_set(values):
    if values is None:
        return set()
    if isinstance(values, set):
        return set(values)
    if isinstance(values, (list, tuple)):
        return {v for v in values if v is not None}
    return {values}

def _dedupe_preserve_order(values):
    seen = set()
    out_vals = []
    for v in values:
        if v is None:
            continue
        try:
            key = v if hash(v) is not None else repr(v)
        except Exception:
            key = repr(v)
            raise
        if key in seen:
            continue
        seen.add(key)
        out_vals.append(v)
    return out_vals

def _candidate_x_from_obj(obj):
    if obj is None:
        return None
    if isinstance(obj, dict):
        for key in ("xj", "x", "x_val", "xcoord", "candidate_x", "x_value"):
            if key in obj and obj[key] is not None:
                return obj[key]
    return obj if not isinstance(obj, (dict, list, tuple, set)) else None

def _candidate_record_from_x(x, source="mumford_residue", **extra):
    rec = {"xj": x, "source": source}
    rec.update(extra)
    return rec

def _collect_mumford_candidate_x_values(obj, out=None):
    """
    Recursively collect candidate x-values from a Mumford payload.
    """
    if out is None:
        out = []

    if obj is None:
        return out

    if isinstance(obj, dict):
        for key in ("xj", "x", "x_val", "xcoord", "candidate_x", "x_value"):
            if key in obj and obj[key] is not None:
                out.append(obj[key])

        if obj and all(not isinstance(v, dict) for v in obj.values()):
            for k, v in obj.items():
                if isinstance(v, (list, tuple, set)) and not isinstance(k, (list, tuple, set, dict)):
                    out.append(k)

        for value in obj.values():
            _collect_mumford_candidate_x_values(value, out)
        return out

    if isinstance(obj, (list, tuple, set)):
        for value in obj:
            _collect_mumford_candidate_x_values(value, out)
        return out

    return out

def _normalize_markov_mumford_result(result, fallback_step=None):
    """
    Normalize the legacy Mumford-search return payload into a walker-friendly dict.
    """
    out = {
        "candidates": [],
        "candidate_records": [],
        "candidate_xs": set(),
        "new_sections": [],
        "precomputed_residues": None,
        "stats": None,
        "raw_mumford_residues": None,
        "found_xs": set(),
    }

    if result is None:
        return out

    if isinstance(result, dict):
        out["raw_mumford_residues"] = result.get("raw_mumford_residues", result)
        out["precomputed_residues"] = result.get("precomputed_residues", None)
        out["stats"] = result.get("stats", None)
        out["new_sections"] = result.get("new_sections", [])

        for key in (
            "input_n", "vecs", "tower_context", "current_x", "current_y",
            "xi", "yi", "shift", "r_expr", "n_with_roots", "per_n_roots",
        ):
            if key in result:
                out[key] = result[key]

        if "found_xs" in result:
            out["found_xs"] = _as_set(result.get("found_xs"))
        if "candidate_xs" in result:
            out["candidate_xs"] = _as_set(result.get("candidate_xs"))

        raw_candidates = result.get("candidate_records", None)
        if raw_candidates is None:
            raw_candidates = result.get("candidates", None)

        if raw_candidates is not None:
            if isinstance(raw_candidates, (list, tuple)):
                out["candidate_records"] = list(raw_candidates)
            else:
                out["candidate_records"] = [raw_candidates]

        for cand in out["candidate_records"]:
            x = _candidate_x_from_obj(cand)
            if x is not None:
                out["candidate_xs"].add(x)
                out["found_xs"].add(x)

        if not out["candidate_xs"]:
            xs = _collect_mumford_candidate_x_values(out["raw_mumford_residues"], [])
            xs = _dedupe_preserve_order(xs)
            if xs:
                out["candidate_xs"] = set(xs)
                out["candidate_records"] = [_candidate_record_from_x(x) for x in xs]

        if not out["candidate_xs"] and fallback_step is not None:
            xs = _collect_mumford_candidate_x_values(fallback_step, [])
            xs = _dedupe_preserve_order(xs)
            if xs:
                out["candidate_xs"] = set(xs)
                out["candidate_records"] = [_candidate_record_from_x(x, source="fallback_step") for x in xs]

        if not out["candidate_records"] and out["candidate_xs"]:
            out["candidate_records"] = [_candidate_record_from_x(x) for x in out["candidate_xs"]]

        out["candidates"] = list(out["candidate_records"])

        try:
            out["candidate_counts"] = Counter(
                cand.get("xj")
                for cand in out["candidate_records"]
                if isinstance(cand, dict) and cand.get("xj") is not None
            )
        except Exception:
            out["candidate_counts"] = Counter()
            raise

        return out

    if isinstance(result, (tuple, list)):
        items = list(result)
        out["raw_mumford_residues"] = items

        xs = []
        found_xs = set()

        for item in items:
            if isinstance(item, (list, tuple, set)):
                for v in item:
                    if v is not None:
                        found_xs.add(v)
            xs.extend(_collect_mumford_candidate_x_values(item, []))

        xs = _dedupe_preserve_order(xs)

        if not xs and found_xs:
            xs = _dedupe_preserve_order(list(found_xs))

        out["found_xs"] = set(found_xs) if found_xs else set(xs)
        out["candidate_xs"] = set(xs)
        out["candidate_records"] = [{"xj": x, "source": "mumford_residue"} for x in xs]
        out["candidates"] = list(out["candidate_records"])

        for item in reversed(items):
            if isinstance(item, dict):
                if out["stats"] is None and "stats" in item:
                    out["stats"] = item["stats"]
                if out["precomputed_residues"] is None and "precomputed_residues" in item:
                    out["precomputed_residues"] = item["precomputed_residues"]
                if not out["new_sections"] and "new_sections" in item:
                    out["new_sections"] = item["new_sections"]

        try:
            out["candidate_counts"] = Counter(
                cand.get("xj")
                for cand in out["candidate_records"]
                if isinstance(cand, dict) and cand.get("xj") is not None
            )
        except Exception:
            out["candidate_counts"] = Counter()
            raise

        return out

    xs = _collect_mumford_candidate_x_values(result, [])
    xs = _dedupe_preserve_order(xs)
    out["raw_mumford_residues"] = result
    out["candidate_xs"] = set(xs)
    out["found_xs"] = set(xs)
    out["candidate_records"] = [{"xj": x, "source": "scalar_fallback"} for x in xs]
    out["candidates"] = list(out["candidate_records"])

    try:
        out["candidate_counts"] = Counter(xs)
    except Exception:
        out["candidate_counts"] = Counter()
        raise

    return out

def _normalize_candidate_output(result):
    """
    Normalize any search result into the walker-friendly dict shape.
    """
    if result is None:
        return {
            "candidates": [],
            "candidate_records": [],
            "candidate_xs": set(),
            "new_sections": [],
            "precomputed_residues": None,
            "stats": None,
        }

    if isinstance(result, dict):
        out = dict(result)
        out.setdefault("candidates", [])
        out.setdefault("candidate_records", out.get("candidates", []))
        out.setdefault("candidate_xs", set())
        out.setdefault("new_sections", [])
        out.setdefault("precomputed_residues", None)
        out.setdefault("stats", None)

        if not out.get("candidate_records") and out.get("candidates"):
            out["candidate_records"] = list(out["candidates"])

        if not out.get("candidate_xs"):
            xs = set()
            for cand in out.get("candidate_records", []):
                if isinstance(cand, dict):
                    x = cand.get("xj", None)
                    if x is None:
                        x = cand.get("x", None)
                    if x is None:
                        x = cand.get("candidate_x", None)
                    if x is None:
                        x = cand.get("x_value", None)
                    if x is not None:
                        xs.add(x)
                else:
                    if cand is not None:
                        xs.add(cand)
            out["candidate_xs"] = xs

        return out

    if isinstance(result, (tuple, list)) and len(result) == 4:
        a, b, c, d = result
        if isinstance(a, list) and a and isinstance(a[0], dict):
            xs = {cand.get("xj") for cand in a if cand.get("xj") is not None}
            return {
                "candidates": a,
                "candidate_records": a,
                "candidate_xs": xs,
                "new_sections": b,
                "precomputed_residues": c,
                "stats": d,
            }
        if isinstance(a, (set, list, tuple)):
            records = [{"xj": x} for x in a]
            return {
                "candidates": records,
                "candidate_records": records,
                "candidate_xs": set(a),
                "new_sections": b,
                "precomputed_residues": c,
                "stats": d,
            }

    raise TypeError(f"Unsupported search result type: {type(result)!r}")

def make_project_markov_search_fn(
    *,
    coeffs_genus2=None,
    base_points=None,
    p: Optional[int] = None,
    prime_pool=None,
    sconf=None,
    num_subsets: Optional[int] = None,
    num_workers: Optional[int] = None,
    debug: bool = False,
    max_n: int = 80,
    precomputed_residues=None,
    all_found_x=None, pool=None, chunk_size=8
):
    """Build a search function that rebuilds the tower for every current x."""
    coeffs_genus2 = coeffs_genus2 if coeffs_genus2 is not None else resolve_project_symbol('COEFFS_GENUS2', required=True)
    p = FINITE_FIELD
    prime_pool = PRIME_POOL
    num_workers = 20
    all_found_x = set()

    def search_fn(xi=None, current_x=None, n=None, seed=None, current_point=None, walker=None, **kwargs):
        if current_point is not None and isinstance(current_point, (tuple, list)) and len(current_point) >= 2:
            x_here, y_here = current_point[0], current_point[1]
        else:
            x_here = xi if xi is not None else current_x
            y_here = None
            if walker is not None and hasattr(walker, 'current_y'):
                y_here = walker.current_y
            if y_here is None:
                yfun = get_y_unshifted_genus2
                if yfun is not None:
                    y_here = yfun(x_here)

        ctx = build_project_tower_context_for_point(
            x_here,
            y_here,
            coeffs_genus2=coeffs_genus2,
            base_points=base_points if base_points is not None else getattr(walker, 'base_points', None),
            p=p,
            debug=debug,
        )

        assert ctx['search_rhs_list'] != ['INF'], ctx

        if debug:
            for k in ctx:
                print(k, ctx[k])

        n0 = int(n or 1)
        vecs = generate_ff_search_vectors(1)
        if not vecs:
            vecs = [tuple([n0])]

        raw = _run_markov_mumford_search_for_point(
            cd=ctx['cd'],
            current_sections=ctx['current_sections'],
            prime_pool=prime_pool,
            vecs=vecs,
            rhs_list=ctx['search_rhs_list'],
            shift=ctx['shift'],
            rationality_test_func=ctx['testfunc'],
            coeffs_genus2=coeffs_genus2,
            tower_data=ctx['tower_for_mumford'],
            num_workers=num_workers,
            debug=debug,
            x_b=None,
            shifted_coeffs=None, pool=pool, chunk_size=chunk_size
        )

        norm = _normalize_markov_mumford_result(raw, fallback_step=ctx)

        # Fertility: fraction of n-values (vecs) that had at least one F_p root across any prime.
        # precomputed_residues[p] is keyed only by v_tuples that had roots, so union of keys = fertile set.
        # We try two possible shapes: {prime: {vtup: solutions}} and the flat {vtup: solutions} fallback.
        _precomp = norm.get('precomputed_residues') or (raw.get('precomputed_residues') if isinstance(raw, dict) else None)
        if _precomp and vecs:
            fertile_vtups = set()
            per_n_root_counts: Dict[str, int] = {}  # vtup_str -> number of F_p roots for that n
            # Shape A: {prime: {vtup: solutions}}  (expected from markov_mode search)
            for p_entry in _precomp.values():
                if isinstance(p_entry, dict):
                    fertile_vtups.update(p_entry.keys())
                    for vtup, solutions in p_entry.items():
                        k = str(vtup)
                        if isinstance(solutions, (list, tuple, set)):
                            cnt = len(solutions)
                        elif solutions is not None:
                            cnt = 1
                        else:
                            cnt = 0
                        # Take max across primes (FF mode has 1 prime; guard for multi-prime callers)
                        if cnt > 0:
                            per_n_root_counts[k] = max(per_n_root_counts.get(k, 0), cnt)
            # Shape B: flat {vtup: solutions} — if Shape A found nothing
            if not fertile_vtups:
                for k, v in _precomp.items():
                    if not isinstance(v, dict):
                        fertile_vtups.add(k)
                        per_n_root_counts[str(k)] = 1
            norm['n_with_roots'] = len(per_n_root_counts)
            norm['n_total'] = len(vecs)
            norm['total_roots'] = sum(per_n_root_counts.values())
            norm['per_n_roots'] = per_n_root_counts  # {vtup_str: root_count}
        else:
            # Fallback filled in below, after enriched_candidates is assembled.
            norm['n_with_roots'] = None
            norm['n_total'] = len(vecs) if vecs else None
            norm['total_roots'] = None

        # Grab ingredients for xk computation.
        # f_i is in R_xm = PolynomialRing(Frac(GF(p)['m']), 'x') — poly in x with rational-function-in-m coefficients.
        # shifted_G_poly is the curve poly in x over GF(p).
        # At a specific m_val: evaluate each coeff of f_i at m=m_val -> univariate poly in x over GF(p).
        # Then G(x) - f_i(x, m_val) = 0 has roots xi(x3), xj, xk.
        _G_poly = ctx.get('shifted_G_poly')
        _tower = ctx.get('primary_tower')
        _fi = None
        if _tower and isinstance(_tower, (list, tuple)) and len(_tower) > 0:
            last = _tower[-1]
            if isinstance(last, dict):
                _fi = last.get('f_i')

        # Curve degree from project globals, defaulting to 5.
        _curve_degree = int(resolve_project_symbol('CURVE_DEGREE', default=5))

        # Helper: check whether xk is an F_p point on C (y^2 = G(xk) must be a QR).
        # Tower construction requires an F_p point; xk's x-coord is in F_p by Vieta but
        # y might only exist over F_{p^2}.  We verify before injecting xk as a chain head.
        def _xk_is_fp_point(xk_val):
            if _G_poly is None or xk_val is None:
                return False
            try:
                rhs = _G_poly(xk_val)
                return bool(rhs.is_square())
            except Exception:
                raise
                return False

        enriched_candidates = []
        for cand in norm.get('candidate_records', []) or norm.get('candidates', []):
            rec = dict(cand) if isinstance(cand, dict) else {'xj': cand}
            rec.setdefault('xj', rec.get('x', None))
            rec['input_n'] = n0
            rec['xi'] = x_here
            rec['yi'] = y_here

            xj_val = rec.get('xj')

            # Skip degenerate candidates where xj == xi (walker would step to itself)
            if xj_val is not None and xj_val == x_here:
                continue

            # Recover m from the linear relation xj = -m + xi  =>  m = xi - xj
            if rec.get('m') is None and xj_val is not None:
                try:
                    rec['m'] = x_here - xj_val
                except Exception:
                    raise

            # Compute xk now while tower context is available.
            if rec.get('xk') is None:
                m_val = rec.get('m')
                if m_val is not None and xj_val is not None:
                    rec['xk'], inter = compute_xk_from_fiber(x_here, m_val, xj_val, _fi, _G_poly, _curve_degree)
                    rec['intersection_poly'] = inter
            # S_of_m is a property of the fibration (fi, G_poly) alone — independent of
            # which (m, xj) candidate we're on.  Compute once and attach to every rec.
            if rec.get('S_of_m') is None and _fi is not None and _G_poly is not None:
                S_of_m, inter_sym = compute_S_of_m(_fi, _G_poly, _curve_degree)
                rec['S_of_m'] = S_of_m
                rec['inter_sym'] = inter_sym

            enriched_candidates.append(rec)

            # Inject xk as an alternative chain head if it is a genuine F_p point on C.
            # xk's x-coordinate is always in F_p (computed via Vieta over F_p), but the
            # y-coordinate only exists over F_p if G(xk) is a QR.  We check this before
            # injecting so that tower construction (which needs an F_p point) will succeed.
            xk_val = rec.get('xk')
            if (xk_val is not None
                    and xk_val != x_here
                    and xk_val != xj_val
                    and _xk_is_fp_point(xk_val)):
                xk_head = {
                    'xj': xk_val,
                    'xk': xj_val,   # the original xj becomes xk in the reversed record
                    'm': x_here - xk_val,   # m' = xi - xk for record-keeping consistency
                    'source': 'xk_head',
                    'input_n': n0,
                    'xi': x_here,
                    'yi': y_here,
                }
                enriched_candidates.append(xk_head)
        # candidate_xs is the set of xj values derived from actual m-roots only.
        # xk_head records must be excluded here so the leaf-tracking in
        # _step_from_candidate_search can separate xj_set (m-root derived) from
        # xk_set (Vieta derived).  xk_head entries are still in enriched_candidates
        # and eligible for the Metropolis chooser.
        candidate_xs = {
            c.get('xj') for c in enriched_candidates
            if isinstance(c, dict)
            and c.get('xj') is not None
            and c.get('source') != 'xk_head'
        }

        # Deferred fertility fallback: if precomputed_residues wasn't available, use
        # the m-root-derived candidate count as a lower-bound proxy.
        # Do NOT include xk_head records in this count — they are not m-roots.
        if norm.get('n_with_roots') is None and vecs:
            n_mroot_cands = sum(
                1 for c in enriched_candidates
                if isinstance(c, dict) and c.get('source') != 'xk_head'
            )
            if n_mroot_cands > 0:
                norm['n_with_roots'] = min(n_mroot_cands, len(vecs))
                norm['n_total'] = len(vecs)
                norm['total_roots'] = n_mroot_cands
                norm['per_n_roots'] = {}  # per-vec provenance not available without precomputed_residues

        n_xk_head = sum(1 for c in enriched_candidates
                        if isinstance(c, dict) and c.get('source') == 'xk_head')

        S_of_m_step, _ = compute_S_of_m(_fi, _G_poly, _curve_degree) if _fi is not None else (None, None)
        result = {
            'candidates': enriched_candidates,
            'candidate_records': enriched_candidates,
            'candidate_xs': candidate_xs,       # xj-only (m-root derived), for leaf tracking
            'n_xk_head': n_xk_head,             # how many xk_head alternatives were injected
            'stats': norm.get('stats', None),
            'found_xs': norm.get('found_xs', set()),
            'input_n': n0,
            'S_of_m': S_of_m_step,   # fibration property of this xi, not of any xj
            'vecs': vecs,
            'n_with_roots': norm.get('n_with_roots', None),
            'n_total': norm.get('n_total', None),
            'total_roots': norm.get('total_roots', None),
            'per_n_roots': norm.get('per_n_roots', None),
            # Memory Fix: Omit 'context', 'raw_mumford_residues', 'new_sections', 'precomputed_residues'
            # which hold uncollectable SageMath Rings and Ideals.
        }

        return result

    return search_fn

def poly_roots_with_multiplicity(poly) -> List[Tuple[Any, int]]:
    """Return roots as (root, multiplicity) pairs over the polynomial's base field."""
    roots = poly.roots(multiplicities=True)
    assert roots, roots
    return [(r, int(m)) for r, m in roots]

def safe_solve_univariate_roots(poly, ring=None) -> List[Any]:
    """Solve poly=0 in its base ring, returning roots if Sage can see them."""
    roots = poly.roots(multiplicities=False)
    assert roots, roots
    return list(roots)

def compute_fertility(norm, raw, vecs):
    precomp = norm.get('precomputed_residues') or (
        raw.get('precomputed_residues') if isinstance(raw, dict) else None
    )

    if not (precomp and vecs):
        return {
            'n_with_roots': None,
            'n_total': len(vecs) if vecs else None,
            'total_roots': None,
            'per_n_roots': None,
        }

    fertile = set()
    per_n = {}

    for entry in precomp.values():
        if isinstance(entry, dict):
            fertile.update(entry.keys())
            for vtup, sols in entry.items():
                k = str(vtup)
                cnt = len(sols) if isinstance(sols, (list, tuple, set)) else (1 if sols else 0)
                if cnt > 0:
                    per_n[k] = max(per_n.get(k, 0), cnt)

    if not fertile:
        for k, v in precomp.items():
            if not isinstance(v, dict):
                fertile.add(k)
                per_n[str(k)] = 1

    return {
        'n_with_roots': len(per_n),
        'n_total': len(vecs),
        'total_roots': sum(per_n.values()),
        'per_n_roots': per_n,
    }

def enrich_candidates(
    norm,
    x_here,
    y_here,
    n0,
    fi,
    G_poly,
    curve_degree,
):
    enriched = []

    for cand in norm.get('candidate_records', []) or norm.get('candidates', []):
        rec = dict(cand) if isinstance(cand, dict) else {'xj': cand}

        rec.setdefault('xj', rec.get('x'))
        rec['input_n'] = n0
        rec['xi'] = x_here
        rec['yi'] = y_here

        xj = rec.get('xj')

        if xj is not None and xj == x_here:
            continue

        # recover m
        if rec.get('m') is None and xj is not None:
            rec['m'] = x_here - xj

        # compute xk
        if rec.get('xk') is None:
            m_val = rec.get('m')
            if m_val is not None and xj is not None:
                xk_val, inter = compute_xk_from_fiber(
                    x_here, m_val, xj, fi, G_poly, curve_degree
                )
                rec['xk'] = xk_val
                rec['intersection_poly'] = inter

        enriched.append(rec)

        # inject xk-head
        xk = rec.get('xk')
        if (
            xk is not None
            and xk != x_here
            and xk != xj
            and xk_is_fp_point(xk, G_poly)
        ):
            enriched.append({
                'xj': xk,
                'xk': xj,
                'm': x_here - xk,
                'source': 'xk_head',
                'input_n': n0,
                'xi': x_here,
                'yi': y_here,
            })

    return enriched

def xk_is_fp_point(xk_val, G_poly):
    if G_poly is None or xk_val is None:
        return False

    try:
        rhs = G_poly(xk_val)
        return bool(rhs.is_square())
    except Exception:
        raise

def compute_S_of_m(fi, G_poly, curve_degree):
    """Return the x^(d-1) coefficient of (G(x) - f_i(x, m)) as a symbolic
    rational function in m, without evaluating m numerically.

    fi lives in R_xm = PolynomialRing(Frac(GF(p)['m']), 'x'), so its
    coefficients are already rational functions in m.  G_poly lives in
    GF(p)[x] with constant coefficients.  We lift G into the same ring and
    subtract to get the bivariate intersection polynomial, then read off the
    x^(d-1) coefficient.

    Returns (S_of_m, inter_sym) where:
      S_of_m   -- negated x^(d-1) coeff of monic inter, a rational function in m
      inter_sym -- full symbolic intersection poly in R_xm[x]

    Returns (None, None) if fi or G_poly are unavailable.
    """
    if fi is None or G_poly is None:
        return None, None
    try:
        R_xm = fi.parent()                          # PolynomialRing(Frac(Fp[m]), 'x')
        base = R_xm.base_ring()                     # Frac(Fp[m])
        # Lift G_poly coefficients into Frac(Fp[m]) so subtraction is valid.
        G_lifted = R_xm([base(c) for c in G_poly.list()])
        inter_sym = G_lifted - fi
        lc = inter_sym.leading_coefficient()
        monic_sym = inter_sym / lc
        deg = int(monic_sym.degree())
        coeffs = monic_sym.list()                   # low-to-high
        # x^(d-1) coeff is at index deg-1; sum-of-roots = -that coeff
        a_dm1 = coeffs[deg - 1] if deg - 1 < len(coeffs) else base(0)
        S_of_m = -a_dm1
        return S_of_m, inter_sym
    except Exception:
        raise

def compute_xk_from_fiber(xi_val, m_val, xj_val, fi, G_poly, curve_degree):
    if fi is None or G_poly is None or m_val is None:
        return None, None

    try:
        Rx = G_poly.parent()
        Fp = Rx.base_ring()
        m_fp = Fp(m_val)

        def eval_at_m(obj):
            try:
                return obj(m_fp) if callable(obj) else obj
            except TypeError:
                raise
                return obj

        coeffs = []
        for c in fi.list():
            num = c.numerator()
            den = c.denominator()

            nv = eval_at_m(num)
            dv = eval_at_m(den)

            dv_fp = Fp(dv)
            if dv_fp == Fp(0):
                return None, None

            coeffs.append(Fp(nv) / dv_fp)

        fi_at_m = Rx(coeffs)
        inter = G_poly - fi_at_m

        if inter.degree() != curve_degree:
            return None, None

        xi_mult = curve_degree - 2
        known = [xi_val] * xi_mult + [xj_val]
        return missing_root_by_vieta(inter, known), inter

    except Exception:
        raise

if __name__ == "__main__":
    raise SystemExit(main())

