import itertools, math, bounds, warnings, sys
from collections import Counter
from sympy import symbols, expand
from sage.all import *
from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
from search_common import *
from tate import *
from search_lll import *
from sat import *
from picard import *
from automorph import *
from torsion import *
from nslattice import *
from yau import *
from bounds import *
from selmer import *
from stats import *
from consensus import *
from mobius import *
from sage.misc.verbose import set_verbose
import dataclasses as _dc

# search7_genus2.sage
# This file was *autogenerated* from the file search7_genus2.sage
# application modules
load('tower.sage')
MARKOV = True
# Suppress the specific "ambiguous form" warning from Sage's Monsky-Washnitzer code

# =============================================================================
# main_genus2: outer loop over fibrations
# =============================================================================

def _print_mode_banner():
    print("finite field:", FINITE_FIELD)
    if FINITE_FIELD is not None:
        print(f"\n{'='*70}")
        print(f"FINITE FIELD MODE: GF({FINITE_FIELD})")
        print(f"Goal: Solve HECC DLP via index calculus on Jacobian")
        print(f"{'='*70}\n")
    else:
        print(f"\n{'='*70}")
        print(f"RATIONAL POINT SEARCH MODE (QQ)")
        print(f"Goal: Find all rational points up to termination threshold")
        print(f"{'='*70}\n")


def _seed_known_points(initial_xs):
    """
    (x, y) and (x, -y) for every seed x that lies on the curve, over GF(p) in
    finite-field mode and over QQ otherwise.

    The genus-2 curve is y^2 = G(x), so (x, -y) is a point whenever (x, y) is
    and y != 0.  The search doesn't rediscover this "for free" -- it already
    knows this x-coordinate, so no (m, vector) candidate will ever surface it
    -- so it has to be added by hand here.
    """
    ff = FINITE_FIELD is not None
    K = GF(FINITE_FIELD) if ff else QQ
    known_pts = set()
    for x in initial_xs:
        y = get_y_unshifted_genus2(K(x) if ff else x)
        if y is None:
            continue
        known_pts.add((K(x), y))
        if y != 0:
            known_pts.add((K(x), -y))
    return known_pts


def _fibration_has_y_zero_point(data_pts):
    """Fibrations built from y=0 points present problems for this method."""
    return any(not pt[1] for pt in data_pts)


def _update_known_points_after_fibration(known_pts, all_found_x, found_from_fibration):
    """Returns the new known_pts (FF mode mutates in place; QQ mode rebuilds via augment_known)."""
    if FINITE_FIELD is not None:
        # In FF mode, update known_pts directly with found coordinates
        for x_coord in found_from_fibration:
            y_coord = get_y_unshifted_genus2(x_coord)
            if y_coord is not None:
                known_pts.add((x_coord, y_coord))
                if y_coord != 0:
                    known_pts.add((x_coord, -y_coord))
        return known_pts
    return augment_known(known_pts, all_found_x, deg6=True)


def _print_final_summary(cumulative_stats, known_pts, all_found_x, terminate_when):
    print("\n" + "="*70)
    print("FINAL SUMMARY")
    print("="*70)

    print("\n--- Cumulative Run Statistics ---")
    print(cumulative_stats.summary_string())

    if FINITE_FIELD is not None:
        print("\n--- Finite Field Results ---")
        print(f"Field: GF({FINITE_FIELD})")
        print(f"Factor base size: {len(all_found_x)}")
        print(f"Total Jacobian elements processed: {len(known_pts)}")
        print("\nNote: In FINITE_FIELD mode, the 'found points' are factor base elements")
        print("used for the index calculus attack, not rational points over Q.")
    else:
        print("\n--- Rational Point Search Results ---")
        print(f"Final list of known points ({len(known_pts)} total):")
        max_h_x = 0.0
        max_h_x_pt = None
        for pt in sorted(list(known_pts)):
            h_x = naive_height_of_rational(pt[0])
            print(f"  {pt}   (naive x-height h(x) ≈ {h_x:.2f}, ~10^{log10_of_naive_height(h_x):.1f} digits)")
            if h_x > max_h_x:
                max_h_x = h_x
                max_h_x_pt = pt
        if max_h_x_pt is not None:
            print(f"\nMax naive x-height reached this run: h(x) ≈ {max_h_x:.2f} "
                  f"(~10^{log10_of_naive_height(max_h_x):.1f} digits), at point {max_h_x_pt}. "
                  f"This is the honest 'how far out did we actually search' number -- "
                  f"it reflects only points found, not what HEIGHT_BOUND nominally allows.")

        if len(known_pts) >= terminate_when:
            print(f"\n✓ Reached termination threshold ({terminate_when} points)")
        else:
            print(f"\n⚠️  Did not reach termination threshold ({len(known_pts)}/{terminate_when})")

    print("="*70)


@PROFILE
def main_genus2():
    """
    Main search function for genus 2 curves.

    Two modes:
    - QQ mode (FINITE_FIELD=None): Exhaustive rational point search
    - Finite field mode (FINITE_FIELD=p): HECC DLP attack via index calculus

    Repeatedly picks a set of known points, builds a fibration from them
    (doloop_genus2), and folds whatever it finds back into the known points,
    until enough points are known or every combination has been tried.
    FINITE_FIELD and MUMFORD_SEARCH runs use exactly one fibration.
    """
    _print_mode_banner()

    initial_xs = DATA_PTS_GENUS2
    print("initial x's:", initial_xs)

    known_pts = add_y_zero_points_to_known(_seed_known_points(initial_xs), COEFFS_GENUS2)
    terminate_when = TERMINATE_WHEN_6
    print("known_pts start:", known_pts)

    excluded = set()
    all_found_x = {pt[0] for pt in known_pts}
    cumulative_stats = SearchStats()

    while True:
        if not FINITE_FIELD and len(known_pts) >= terminate_when:
            print(f"\nTERMINATE_WHEN_6 ({terminate_when}) reached.")
            break

        data_pts = get_data_pts(known_pts, excluded)
        if data_pts is None:
            print("\nAll combinations of points have been checked.")
            break

        if _fibration_has_y_zero_point(data_pts):
            excluded.add(frozenset(data_pts))
            print("Skipping:", data_pts, "due to the presence of y=0 point.")
            continue

        print("\n" + "="*70)
        print(f"Constructing new fibration using: {data_pts}")
        print(f"Known pts so far: {sorted(list(known_pts))}")
        if not FINITE_FIELD:
            print(f"Found {len(known_pts)} / {terminate_when}")
        print("="*70 + "\n")

        found_from_fibration, cumulative_stats = doloop_genus2(
            data_pts, COEFFS_GENUS2, all_found_x, cumulative_stats
        )

        all_found_x.update(found_from_fibration)
        excluded.add(frozenset(data_pts))
        known_pts = _update_known_points_after_fibration(known_pts, all_found_x, found_from_fibration)

        if FINITE_FIELD:
            print("\n" + "="*70)
            print("FINITE FIELD MODE: Completed DLP attack on single fibration")
            print("="*70)
            break

        if MUMFORD_SEARCH:
            print("\nMUMFORD_SEARCH mode: Only trying one fibration for basis search")
            break

    _print_final_summary(cumulative_stats, known_pts, all_found_x, terminate_when)

def find_y_zero_points_genus2(sextic_coeffs, verbose=True):
    """
    Find all rational points (x,0) on the genus 2 curve y^2 = G(x).
    For y=0, we need G(x) = 0.

    - In QQ mode: Returns rational (x, 0) points
    - In finite field mode: Returns GF(p) points where G(x) = 0

    Args:
        sextic_coeffs: List of coefficients [a6, a5, a4, a3, a2, a1, a0]
        verbose: Print debug information

    Returns:
        Set of points (x, 0) where G(x) = 0
    """
    if verbose:
        print("\n--- Searching for y=0 points ---")

    if FINITE_FIELD is not None:
        # Finite field mode
        F = GF(FINITE_FIELD)
        R_x = PolynomialRing(F, 'x')
        x_var = R_x.gen()
        G = sum(F(a) * x_var**(len(sextic_coeffs)-1-i)
                for i, a in enumerate(sextic_coeffs))

        if verbose:
            print(f"hyperelliptic curve: y^2 = {G}")

        # Find all roots in F
        roots = G.roots(multiplicities=False)
        y_zero_points = {(F(root), F(0)) for root in roots}

        if verbose:
            if y_zero_points:
                print(f"Found {len(y_zero_points)} points where y=0: {sorted(list(y_zero_points))}")
            else:
                print("No points found where y=0")

    else:
        # Rational (QQ) mode - original logic
        R_x = QQ['x']
        G = sum(a * R_x.gen()**(len(sextic_coeffs)-1-i)
                for i, a in enumerate(sextic_coeffs))

        if verbose:
            print(f"hyperelliptic curve: y^2 = {G}")

        # Find all rational roots
        rational_roots = G.roots(QQ, multiplicities=False)
        y_zero_points = {(QQ(root), QQ(0)) for root in rational_roots}

        if verbose:
            if y_zero_points:
                print(f"Found {len(y_zero_points)} points where y=0: {sorted(list(y_zero_points))}")
            else:
                print("No rational points found where y=0")

    return y_zero_points

@PROFILE
def analyze_fibration_geometry(fib_data, base_pts, height_bound, shift, all_known_x, global_sconf, seed=None, primary_deg=12):
    """
    Analyze single fibration tower. In FINITE_FIELD mode this function avoids SR entirely
    and returns field-native objects (Fm polynomials, etc).
    """
    tower = fib_data['tower']
    fib_id = fib_data.get('id', 0)
    seed = fib_data.get('seed', seed)

    print(f"  [analyze_fibration] Analyzing geometry for tower (seed={seed}, id={fib_id})...")

    # Determine base field
    if FINITE_FIELD:
        base_field = GF(FINITE_FIELD)
    else:
        base_field = QQ

    PR_m = PolynomialRing(base_field, 'm')
    m_poly = PR_m.gen()
    Fm = PR_m.fraction_field()
    R_x_m, x_poly = PolynomialRing(Fm, 'x').objgen()

    # Extract roots and final RHS polynomial from tower
    # In FINITE_FIELD mode the tower entries should already be field-native
    this_roots = [step['r_expr'] for step in tower]
    this_E_rhs_obj = tower[-1]['f_i']   # expected: polynomial over Fm[x] (field-native) or symbolic for QQ

    # Build field-native E_rhs_m
    if FINITE_FIELD:
        # If it's already an R_x_m polynomial, keep it
        if this_E_rhs_obj.parent() == R_x_m:
            this_E_rhs_m = this_E_rhs_obj
        else:
            # Try to extract coefficient list and coerce into R_x_m
            coeffs = list(this_E_rhs_obj.list())
            coeffs_in_Fm = [Fm(c) for c in coeffs]
            this_E_rhs_m = R_x_m(coeffs_in_Fm)

    else:
        # QQ / symbolic branch - preserve previous behaviour (uses SR)
        this_E_rhs_m = None  # retain existing code path below (handled in QQ mode)

    # For both modes: construct curve data and compute geometry
    if FINITE_FIELD:
        this_E_curve_m, one, two, three = compute_morphism(this_E_rhs_m)
        # lastrhs: evaluate at last root (roots stored as field native)
        lastrhs = this_E_rhs_m(x=this_roots[-1])
        last_phi_x = get_phi_x(one, two, three, this_roots[-1], lastrhs)
        this_cd = buildcd(this_E_curve_m, last_phi_x, lastrhs, this_E_rhs_m, (one, two, three))
    else:
        # QQ / SR mode: fall back to old behaviour (unchanged)
        # Keep SR-based reconstruction for compatibility
        xSR, mSR = SR.var('x'), SR.var('m')
        this_roots_sr = [SR(step['r_expr']) for step in tower]
        this_E_rhs_sym = this_E_rhs_obj
        coeffs_in_m = [SR(this_E_rhs_sym).coefficient(xSR, i) for i in range(SR(this_E_rhs_sym).degree(xSR) + 1)]
        coeffs_in_Fm = [PR_m.frac_field()(c.subs({mSR: m_poly})) for c in coeffs_in_m]
        E_rhs_m = R_x_m(coeffs_in_Fm)
        this_E_curve_m, one, two, three = compute_morphism(E_rhs_m)
        lastrhs = E_rhs_m(x=this_roots_sr[-1])
        last_phi_x = get_phi_x(one, two, three, this_roots_sr[-1], lastrhs)
        this_cd = buildcd(this_E_curve_m, last_phi_x, lastrhs, E_rhs_m, (one, two, three))

    # --- KEY FIX: compute discriminant degree safely ---
    Delta = this_cd.E_weier.discriminant()
    if hasattr(Delta, 'numerator'):
         this_disc_deg = Delta.numerator().degree()
    else:
         this_disc_deg = Delta.degree()

    is_primary = (fib_id == -1)
    scaling_factor = float(this_disc_deg) / float(primary_deg)

    if is_primary:
        this_height_bound = height_bound
        print(f"  [analyze_fibration] Using PRIMARY height bound: {this_height_bound}")
    else:
        this_height_bound = int(height_bound * scaling_factor * 1.2)
        print(f"  [analyze_fibration] Scaling height bound: {height_bound} -> {this_height_bound} (deg ratio {scaling_factor:.2f})")

    # Auto-configure search params (uses this_cd)
    known_pts_for_height = [(QQ(x), None) for x in all_known_x if x is not None]
    known_pts_for_height.extend([(QQ(pt[0]), QQ(pt[1])) for pt in base_pts if pt[0] is not None])
    if not known_pts_for_height:
        known_pts_for_height = [(QQ(0), None)]

    this_sconf = bounds.auto_configure_search(
                this_cd,
                known_pts_for_height,
                height_bound=None,
                run_heavy_analysis=False,
                debug=False
            )
    this_sconf['HEIGHT_BOUND'] = this_height_bound
    print(f"  [analyze_fibration] Configured with H_bound={this_height_bound}")

    # 5. Compute sections and reduce
    fib_specific_sections = compute_base_sections_m(this_cd, base_pts)
    if not fib_specific_sections:
        print(f"  [analyze_fibration] ERROR: Could not compute base sections.")
        return None

    fib_specific_sections = lll_reduce_mw_basis(this_cd, fib_specific_sections)

    # 6. Height matrix and vectors
    independent, this_H = check_independence(fib_specific_sections, this_E_curve_m, this_cd)
    if not independent:
        print(f"  [analyze_fibration] ERROR: Section basis is linearly dependent.")
        return None

    print(f"  [analyze_fibration] Fibration H:\n{this_H}")

    if FINITE_FIELD:
        fib_specific_vecs = generate_ff_search_vectors(len(fib_specific_sections))
    else:
        fib_specific_vecs = compute_search_vectors(this_H, this_height_bound)

    fib_specific_vecs = canonicalize_by_sign(fib_specific_vecs)
    print(f"  [analyze_fibration] Found {len(fib_specific_vecs)} search vectors (H={this_height_bound}).")

    # 7. Build rhs_list (field-native where possible)
    this_search_rhs_list = []

    if FINITE_FIELD:
        # In FF mode, put field-native phi_x if available; otherwise string fallback
        this_search_rhs_list.append(this_cd.phi_x)
        # For other roots produce phi_x evaluated objects where possible
        for root_val in this_roots[:-1]:
            qrhs_r = this_E_rhs_m(x=root_val)
            phi_x_r = get_phi_x(one, two, three, root_val, qrhs_r)
            this_search_rhs_list.append(phi_x_r)
    else:
        # symbolic branch (kept for compatibility)
        xSR, mSR = SR.var('x'), SR.var('m')
        this_search_rhs_list = [SR(this_cd.phi_x)]
        for root in this_roots[:-1]:
            qrhs_r = SR(this_E_rhs_obj).subs({xSR: SR(root)})
            phi_x_r_SR = SR(get_phi_x(SR(one), SR(two), SR(three), SR(root), qrhs_r))
            this_search_rhs_list.append(phi_x_r_SR)

    return {
        'cd': this_cd,
        'sections': fib_specific_sections,
        'H': this_H,
        'height_bound': this_height_bound,
        'vecs': fib_specific_vecs,
        'rhs_list': this_search_rhs_list,
        'r_m': this_roots[0],
        'sconf': this_sconf,
        'deg': this_disc_deg,
        'disc_deg': this_disc_deg,
        'name': f"fib_seed_{seed}",
    }

@PROFILE
def scancd_for_special_fibers(cd, r_m, shift):
    """scan singular and other special fibers for m values which may give rational points"""
    singfibs = cd.singfibs
    fibers = singfibs['fibers']
    euler = singfibs['euler_characteristic']
    sigma = singfibs['sigma_sum']
    singular_fibers_m = [f['r'] for f in fibers if (f.get('root_type') == 'rational' or f.get('root_type') == 'pole')]

    cm_fibers = find_cm_fibers(cd)
    j_targets = [0, 1728, -12**3, -32**3, -96**3]
    special_fibers_m = find_special_j_invariant_fibers(cd, j_targets)
    test_fibers = {m for m in set(singular_fibers_m).union(cm_fibers).union(special_fibers_m) if m is not None}
    print("Testing special m-values from fibers:", test_fibers)
    sys.stdout.flush()

    # Ensure m-values are compatible with the base field of r_m
    if FINITE_FIELD:
        F = GF(FINITE_FIELD)
        test_fibers_list = []
        for val in test_fibers:
            try:
                test_fibers_list.append(F(val))
            except (TypeError, ValueError, ZeroDivisionError):
                # Skip values that cannot be coerced (e.g. poles mod p)
                continue
    else:
        test_fibers_list = list(test_fibers)

    found_from_fibers = test_y_rationality_genus2(test_fibers_list, r_m, shift)

    if found_from_fibers:
        print(f"Points found from special fibers: {found_from_fibers}")
    sys.stdout.flush()
    return found_from_fibers

class SpamFilter:
    def __init__(self, stream):
        self.stream = stream
        self._buffer = ""

    def write(self, data):
        self._buffer += data
        while "\n" in self._buffer:
            line, self._buffer = self._buffer.split("\n", 1)
            if "Returning ambiguous form of degree genus+1." not in line:
                self.stream.write(line + "\n")
                self.stream.flush()

    def flush(self):
        if self._buffer:
            if "Returning ambiguous form of degree genus+1." not in self._buffer:
                self.stream.write(self._buffer)
            self._buffer = ""
        self.stream.flush()

# -------------------------
# Tower builder adapter for search (lightweight, deterministic, no tests)
# -------------------------
# --- Helper Functions ---

# Simple integration into your existing code:

# In doloop_genus2, replace the consensus precomputation section
# (starting from "if USE_CONSENSUS_FILTER and fibrations:")
# with this updated version:

# Replace analyze_fibration_geometry with this version that avoids SR in FINITE_FIELD

@PROFILE
def add_y_zero_points_to_known(known_pts, sextic_coeffs):
    """Add y=0 points to the known points set."""
    y_zero_points = find_y_zero_points_genus2(sextic_coeffs)
    known_pts.update(y_zero_points)
    return known_pts

# In search7_genus2.sage

@PROFILE
def setup_field_and_rings(sextic_coeffs, data_pts):
    """Setup base field, polynomial rings, and initial geometry."""
    if FINITE_FIELD:
        base_field = GF(FINITE_FIELD)
        PR_m = PolynomialRing(base_field, 'm')
        m_poly = PR_m.gen()
        Fm = PR_m.fraction_field()
        R_x = PolynomialRing(base_field, 'x')
        x = R_x.gen()
        G = sum(base_field(a) * x**(len(sextic_coeffs)-1-i)
                for i, a in enumerate(sextic_coeffs))
        real_pts = [(p[0], p[1]) for p in data_pts if p[0] is not None]
    else:
        SR_m = var('m')
        PR_m = PolynomialRing(QQ, 'm')
        m_poly = PR_m.gen()
        Fm = PR_m.fraction_field()
        R_x = PolynomialRing(QQ, 'x')
        x = R_x.gen()
        G = sum(QQ(a) * x**(len(sextic_coeffs)-1-i)
                for i, a in enumerate(sextic_coeffs))
        real_pts = [(QQ(p[0]), QQ(p[1])) for p in data_pts if p[0] is not None]
        base_field = QQ

    return {
        'base_field': base_field,
        'PR_m': PR_m,
        'm_poly': m_poly,
        'Fm': Fm,
        'R_x': R_x,
        'x': x,
        'G': G,
        'real_pts': real_pts
    }

@PROFILE
def apply_shift_transformation(G, real_pts, base_field):
    """Apply shift transformation to avoid zero denominators."""
    shift = base_field(0)
    if not MOBIUS_TRANS:
        while any((base_field(pt[0]) + shift) == 0 for pt in real_pts):
            shift += 1
        if shift:
            print(f"\nSHIFT = {shift}\n")

    shifted_G_poly = G(G.parent().gen() - shift)
    base_pts = [(base_field(X) + shift, base_field(Y)) for X, Y in real_pts]
    print("shifted G poly1:", shifted_G_poly)

    return shifted_G_poly, base_pts, shift

@PROFILE
def apply_mobius_transformation(shifted_G_poly, all_known_x, base_pts):
    """Apply Mobius transformation to the geometry (QQ mode only)."""
    T = None
    T_inv = None

    if not MOBIUS_TRANS:
        return shifted_G_poly, base_pts, T, T_inv, all_known_x

    T = choose_transform(
        shifted_G_poly,
        all_known_x,
        avoid_primes=AVOID,
        prefer_primes=PREFER,
        search_range=15,
        allow_c_nonzero=True
    )
    print(f"[mobius] Using transform: {T}")

    T_inv = MobiusTransform(T.d, -T.b, -T.c, T.a)
    shifted_G_poly = apply_to_poly(shifted_G_poly, T_inv)
    print("shifted G poly:", shifted_G_poly)

    all_known_x = set(apply_to_points(all_known_x, T))
    base_pts_x_only = [pt[0] for pt in base_pts]
    transformed_x = apply_to_points(base_pts_x_only, T)

    updated_base_pts = []
    print("\n[mobius] Updating base points to new curve geometry:")
    for i, (new_x, old_y) in enumerate(zip(transformed_x, [pt[1] for pt in base_pts])):
        if new_x is None:
            updated_base_pts.append((None, None))
            continue

        rhs_val = shifted_G_poly(new_x)
        new_y = QQ(sqrt(rhs_val))
        updated_base_pts.append((new_x, new_y))
        print(f"  ✓ Point {i}: x={new_x} -> y={new_y} (verified on new curve)")

    base_pts = updated_base_pts
    trans_degree = shifted_G_poly.degree()
    print(f"  Transformed polynomial degree: {trans_degree}")

    return shifted_G_poly, base_pts, T, T_inv, all_known_x

@PROFILE
def build_tower_and_fibrations(shifted_G_poly, base_pts):
    """Build primary tower and optional consensus fibrations."""
    current_deg = shifted_G_poly.degree()
    needed_steps = max(0, current_deg - 4)

    print(f"--- Building {needed_steps} Step Fibration Tower (deg {current_deg} -> 4) ---")

    primary_tower = iterate_tower(
        fx_PR=shifted_G_poly,
        pts_xy=base_pts,
        max_steps=needed_steps,
        seed_int=SEED_INT,
        verbose=DEBUG,
        use_anchor_points=False
    )

    fibrations = None
    if USE_CONSENSUS_FILTER and not FINITE_FIELD:
        print(f"\n{'='*70}")
        print(f"MULTI-FIBRATION CONSENSUS MODE")
        print(f"Building {NUM_CONSENSUS_FIBRATIONS} independent fibrations...")
        print(f"{'='*70}")

        fibrations = build_multiple_fibrations(
            fx_PR=shifted_G_poly,
            pts_xy=base_pts,
            num_fibrations=NUM_CONSENSUS_FIBRATIONS,
            max_steps=needed_steps,
            base_seed=SEED_INT+1000,
            verbose=DEBUG
        )

        primary_tower_with_meta = {
            'tower': primary_tower,
            'seed': SEED_INT,
            'id': -1
        }
        fibrations.insert(0, primary_tower_with_meta)

    tower_for_mumford = primary_tower if MUMFORD_SEARCH else None

    return primary_tower, fibrations, tower_for_mumford

@PROFILE
def extract_geometry_from_tower(primary_tower, Fm):
    """Extract roots and RHS from tower, handling both FF and QQ modes."""
    roots = [i['r_expr'] for i in primary_tower]
    E_rhs_obj = primary_tower[-1]['f_i']

    if FINITE_FIELD:
        E_rhs_m = E_rhs_obj
        r_m = roots[0]
        return E_rhs_m, r_m, roots
    else:
        E_rhs_m_symbolic = E_rhs_obj
        m_r = solve(SR(roots[0]) == var('r'), var('m'))[0].rhs()
        r_m = SR(roots[0])

        R_x_m, x_poly = PolynomialRing(Fm, 'x').objgen()
        xSR, mSR = SR.var('x'), SR.var('m')

        coeffs_in_m = [
            SR(E_rhs_m_symbolic).coefficient(xSR, i)
            for i in range(SR(E_rhs_m_symbolic).degree(xSR) + 1)
        ]
        # BUG (fixed): Fm.base_ring() for Fm = Frac(QQ['m']) is QQ, not QQ['m'],
        # so Fm.base_ring().gen() returned QQ's multiplicative generator (the
        # constant 1) rather than the polynomial variable m. Every coefficient
        # was getting mSR substituted with 1, collapsing all m-dependence to
        # plain rationals before E_rhs_m was even built. Use Fm.gen() instead,
        # which is the correct way to get m as an element of Fm (matching the
        # pattern used everywhere else in the codebase, e.g. search_common.py).
        m_in_Fm = Fm.gen()
        coeffs_in_Fm = [Fm(c.subs({mSR: m_in_Fm})) for c in coeffs_in_m]
        E_rhs_m = R_x_m(coeffs_in_Fm)

        return E_rhs_m, r_m, roots

@PROFILE
def build_curve_data(E_rhs_m, roots, base_pts):
    """Build curve data structure from RHS polynomial."""
    fibration_type = f"{len(set(pt[0] for pt in base_pts))}-point"
    print(f"--- Running {fibration_type} Fibration (Primary Geometry) ---")

    E_curve_m, one, two, three = compute_morphism(E_rhs_m)
    lastrhs = E_rhs_m(x=roots[-1])
    last_phi_x = get_phi_x(one, two, three, roots[-1], lastrhs)
    cd = buildcd(E_curve_m, last_phi_x, lastrhs, E_rhs_m, (one, two, three))

    return cd, (one, two, three)

@PROFILE
def configure_search_parameters(cd, all_known_x, base_pts, base_field):
    """Auto-configure search parameters based on curve data."""
    if not FINITE_FIELD:
        print("\n=== Auto-configuring search parameters for this fibration ===")
        print(f"[auto_cfg] Building height estimation from {len(all_known_x)} known x-coords.")

    known_pts_for_height = []
    for x_coord in all_known_x:
        known_pts_for_height.append((QQ(x_coord) if not FINITE_FIELD else base_field(x_coord), None))

    for pt in base_pts:
        if pt[0] is not None:
            known_pts_for_height.append((
                QQ(pt[0]) if not FINITE_FIELD else base_field(pt[0]),
                QQ(pt[1]) if (not FINITE_FIELD and pt[1] is not None) else (base_field(pt[1]) if pt[1] is not None else None)
            ))

    if not known_pts_for_height:
        known_pts_for_height = [(base_field(0), None)]

    sconf = bounds.auto_configure_search(cd, known_pts_for_height, height_bound=None, debug=True)
    print_conf(sconf)

    prime_pool = sconf['PRIME_POOL']
    if not FINITE_FIELD:
        prime_pool = bounds.recommend_and_update_prime_pool(cd, run_heavy=True, grh_fudge=10, debug=True)
    prime_pool = sorted(set(prime_pool))
    if not FINITE_FIELD:
        print(f"[prime_pool] Final pool has {len(prime_pool)} primes up to {max(prime_pool)}")

    return sconf, prime_pool

@PROFILE
def build_search_rhs_list(cd, roots, E_rhs_m_symbolic, one, two, three):
    """Build list of RHS functions for search."""
    k = cd.k_base_change
    n = cd.tate_exponent
    blowup = cd.blowup_factor
    m_sym = cd.a4.parent().gen()
    total_x_scale_factor = m_sym ** (2 * n - 2 * blowup)

    if FINITE_FIELD:
        roots_clean = [r for r in roots if r is not None]
        search_rhs_list = [cd.phi_x]
    else:
        SR_m = var('m')
        roots_clean = [SR(r) for r in roots]

        search_rhs_list = [SR(cd.phi_x)]

        xSR = SR.var('x')
        for i in roots_clean[:-1]:
            qrhs_r = SR(E_rhs_m_symbolic).subs({xSR: i})
            phi_x_r = get_phi_x(SR(one), SR(two), SR(three), i, qrhs_r)
            phi_x_r_SR = SR(phi_x_r)
            rhs_scaled_SR = (phi_x_r_SR.subs({m_sym: m_sym**k}) if k != 0 else phi_x_r_SR) / SR(str(total_x_scale_factor))
            search_rhs_list.append(rhs_scaled_SR)

    n_before = len(search_rhs_list)
    search_rhs_list = [r for r in search_rhs_list if r != "INF"]
    if len(search_rhs_list) < n_before:
        print(f"[build_search_rhs_list] dropped {n_before - len(search_rhs_list)} INF rhs (denominator vanished at root)")

    return search_rhs_list

@PROFILE
def setup_rationality_test_function(shift, T, T_inv):
    """Create appropriate rationality test function based on transformations."""
    def check_rationality_transformed(x_val_search):
        """Maps x_val (from search space) -> x_shifted -> x_original"""
        x_val_q = QQ(x_val_search)
        if T_inv:
            x_shifted = T_inv.apply(x_val_q)
        else:
            x_shifted = x_val_q
        x_original = x_shifted + shift
        return get_y_unshifted_genus2(x_original)

    if T:
        shift = 0
        testfunc = check_rationality_transformed
    else:
        testfunc = get_y_unshifted_genus2

    return testfunc, shift

@PROFILE
def precompute_consensus_residues(fibrations, base_pts, sconf, shift, all_known_x, primary_tower, sextic_coeffs):
    """Precompute residues for all fibrations in consensus mode."""
    print(f"\n{'='*70}")
    print(f"PRECOMPUTING RESIDUES FOR {len(fibrations)} FIBRATIONS")
    print(f"{'='*70}")

    all_precomputed_residues = []
    all_fibration_geometries = []
    primary_height_bound = sconf['HEIGHT_BOUND']
    prime_pool = sconf['PRIME_POOL']

    for fib_idx, fib_data in enumerate(fibrations):
        print(f"\n--- Fibration {fib_idx+1}/{len(fibrations)} (seed={fib_data['seed']}) ---")

        fib_analysis = analyze_fibration_geometry(
            fib_data,
            base_pts,
            primary_height_bound,
            shift,
            all_known_x,
            sconf,
            seed=fib_data['seed']
        )

        r_m = primary_tower[0]['r_expr'] if FINITE_FIELD else SR(primary_tower[0]['r_expr'])
        extra_pts = scancd_for_special_fibers(fib_analysis['cd'], fib_analysis['r_m'], shift)
        if extra_pts:
            all_known_x.update(extra_pts)

        if fib_analysis is None:
            print(f"  Skipping fibration {fib_idx+1} due to analysis error.")
            all_precomputed_residues.append({})
            continue

        this_cd = fib_analysis['cd']
        fib_specific_sections = fib_analysis['sections']
        this_search_rhs_list = fib_analysis['rhs_list']
        fib_specific_vecs = fib_analysis['vecs']

        geom_info = {
            'H': fib_analysis['H'],
            'deg': fib_analysis['deg'],
            'disc_deg': fib_analysis['deg'],
            'name': fib_analysis['name'],
            'cd': this_cd,
            'sections': fib_specific_sections
        }
        all_fibration_geometries.append(geom_info)

        fib_Ep_dict, fib_rhs_modp_list, fib_mult_lll, fib_vecs_lll = prepare_modular_data_lll(
            this_cd,
            fib_specific_sections,
            prime_pool,
            this_search_rhs_list,
            fib_specific_vecs,
            SearchStats(),
            search_primes=prime_pool
        )

        if not fib_Ep_dict:
            print(f"  Warning: No valid primes for fibration {fib_idx+1}, skipping")
            all_precomputed_residues.append({})
            continue

        primes_to_compute = list(fib_Ep_dict.keys())
        num_rhs_fns = len(this_search_rhs_list)
        vecs_list = list(fib_specific_vecs)

        args_list = [
            (
                p,
                fib_Ep_dict[p],
                fib_mult_lll.get(p, {}),
                fib_vecs_lll.get(p, [tuple([0] * len(fib_specific_sections)) for _ in vecs_list]),
                vecs_list,
                fib_rhs_modp_list,
                num_rhs_fns,
                SearchStats()
            )
            for p in primes_to_compute
        ]

        fib_precomputed = {}

        ctx = multiprocessing.get_context("fork")
        exec_kwargs = {"max_workers": 8, "mp_context": ctx}

        with ProcessPoolExecutor(**exec_kwargs) as executor:
            if TORSION_SLOPPY:
                futures = {executor.submit(_compute_residues_for_prime_worker, args): args[0]
                           for args in args_list}
            else:
                futures = {executor.submit(_compute_residues_for_prime_worker_old, args): args[0]
                           for args in args_list}

            for future in tqdm(as_completed(futures), total=len(futures),
                        desc=f"Fib {fib_idx+1}/{len(fibrations)}"):
                p = futures[future]
                p_ret, mapping, local_checks = future.result()
                fib_precomputed[p_ret] = mapping or {}

        all_precomputed_residues.append(fib_precomputed)

    return all_precomputed_residues, all_fibration_geometries

@PROFILE
def apply_consensus_filter(all_precomputed_residues, all_fibration_geometries, prime_pool, r_m, shift):
    """Apply height-aware consensus filter to residues."""
    print(f"\n{'='*70}")
    print("APPLYING HEIGHT-AWARE CONSENSUS FILTER")
    print(f"{'='*70}")

    precomputed_residues, consensus_stats = compute_consensus_residues_with_height_matching(
        all_precomputed_residues,
        all_fibration_geometries,
        prime_pool,
        consensus_threshold=CONSENSUS_THRESHOLD,
        height_tolerance_log=0.1,
        use_delta_scaling=True,
        debug=DEBUG,
        target_x=TARGETED_X if TARGETED_X else None,
        r_m=r_m,
        shift=shift
    )

    print(f"\nConsensus Filter Results:")
    print(f"  Residues: {consensus_stats['total_residues_before']:,} → {consensus_stats['total_residues_after']:,}")
    print(f"  Reduction: {consensus_stats['reduction_ratio']:.1%}")

    return precomputed_residues, consensus_stats

@PROFILE
def run_single_search_iteration(cd, current_sections, E_curve_m, height_bound, prime_pool, sconf,
                                vecs, search_rhs_list, r_m, shift, all_known_x, testfunc,
                                tower_for_mumford, sextic_coeffs, fibrations, base_pts, primary_tower,
                                x_b=None, shifted_coeffs=None, height_pairing_H=None):
    """Run a single iteration of the search loop.

    height_pairing_H: the Shioda-Tate height-pairing matrix H for
    current_sections (H[i][j] = <P_i, P_j>, same ordering as
    current_sections/vecs), if available. Threaded through to the modp
    search so it can build a real per-vector height bound
    (n^2 * height(P) generalized to v^T H v) instead of the flat
    HEIGHT_BOUND constant. None in FINITE_FIELD mode or if the caller
    doesn't have one.
    """
    if SYMBOLIC_SEARCH and not FINITE_FIELD:
        newly_found_x, new_sections = search_lattice_symbolic(
            cd,
            current_sections,
            vecs,
            rhs_list=search_rhs_list,
            r_m=r_m,
            shift=shift,
            all_found_x=all_known_x,
            rationality_test_func=testfunc,
            stats=SearchStats()
        )
        iter_stats = SearchStats()
        return newly_found_x, new_sections, iter_stats

    num_prime_subsets = NUM_PRIME_SUBSETS
    #num_prime_subsets = int(sconf['NUM_PRIME_SUBSETS'])

    if USE_CONSENSUS_FILTER and fibrations and not FINITE_FIELD:
        all_precomputed_residues, all_fibration_geometries = precompute_consensus_residues(
            fibrations, base_pts, sconf, shift, all_known_x, primary_tower, sextic_coeffs
        )

        precomputed_residues, consensus_stats = apply_consensus_filter(
            all_precomputed_residues, all_fibration_geometries, prime_pool, r_m, shift
        )

        result = search_lattice_modp_unified_parallel(
            cd,
            current_sections,
            prime_pool,
            vecs,
            search_rhs_list,
            r_m,
            shift,
            all_known_x,
            num_prime_subsets,
            testfunc,
            sconf, sextic_coeffs,
            tower_data=tower_for_mumford,
            precomputed_residues=precomputed_residues,
            x_b=x_b,
            shifted_coeffs=shifted_coeffs,
            markov_mode=False,
            height_pairing_H=height_pairing_H,
        )
        # search_lattice_modp_unified_parallel returns a 4-tuple in Mumford
        # mode (found_xs, new_sections, precomputed_residues, stats) but a
        # result dict in standard-lattice mode (see run_standard_lattice_search);
        # normalize both to the same local names here.
        if isinstance(result, dict):
            newly_found_x = result["candidate_xs"]
            new_sections = result["new_sections"]
            iter_stats = result["stats"]
        else:
            newly_found_x, new_sections, _, iter_stats = result

        iter_stats.consensus_filter_stats = consensus_stats
    else:

        result = search_lattice_modp_unified_parallel(
            cd,
            current_sections,
            prime_pool,
            vecs,
            search_rhs_list,
            r_m,
            shift,
            all_known_x,
            num_prime_subsets,
            testfunc,
            sconf,
            sextic_coeffs,
            tower_for_mumford,           # Pass positionally
            x_b=x_b,
            shifted_coeffs=shifted_coeffs,
            markov_mode=False,
            height_pairing_H=height_pairing_H,
        )
        if isinstance(result, dict):
            newly_found_x = result["candidate_xs"]
            new_sections = result["new_sections"]
            precomputed_residues = result["precomputed_residues"]
            iter_stats = result["stats"]
        else:
            newly_found_x, new_sections, precomputed_residues, iter_stats = result

    return newly_found_x, new_sections, iter_stats

@PROFILE
def run_qq_mode_diagnostics(cumulative_stats, prime_pool, height_bound, all_known_x, r_m, shift,
                           real_pts, base_pts, T, current_sections, cd, precomputed_residues=None):
    """Run all post-search diagnostics for QQ mode."""
    xtest = base_pts[0][0]
    xtest_unshifted = real_pts[0][0]

    m_r = solve(SR(r_m) == var('r'), var('m'))[0].rhs()
    mtest = m_r(r=xtest)
    assert_base_m_found(mtest, xtest_unshifted, r_m, shift, T=T)

    found_x_list = list(all_known_x)

    print_unified_completeness_report(
        stats=cumulative_stats,
        prime_pool=prime_pool,
        prime_subsets=cumulative_stats.prime_subsets,
        height_bound=height_bound,
        found_xs=found_x_list,
        r_m=r_m,
        shift=shift
    )

    analyzer = FindabilityAnalyzer(cumulative_stats, prime_pool)

    diag = print_unified_diagnostics(
        findability_analyzer=analyzer,
        prime_pool=prime_pool,
        prime_subsets=cumulative_stats.prime_subsets if hasattr(cumulative_stats, 'prime_subsets') else None,
        height_bound=height_bound,
        bootstrap_N=5000,
        bootstrap_max_num=min(10**4, max(10**3, int(2**(height_bound//2)))),
        bootstrap_max_den=min(10**4, max(10**3, int(2**(height_bound//3)))),
        mi_primes_limit=40,
        mi_N=2000
    )

    if TARGETED_X:
        run_targeted_point_analysis(TARGETED_X, r_m, cumulative_stats, prime_pool,
                                   analyzer, precomputed_residues, shift=shift)

    print_search_summary(cumulative_stats, all_known_x)
    run_sufficiency_proof_and_posterior(cumulative_stats, all_known_x, height_bound,
                                       current_sections, prime_pool, diag)
    validate_ramification_locus(cd, cumulative_stats)

@PROFILE
def run_targeted_point_analysis(TARGETED_X, r_m, cumulative_stats, prime_pool, analyzer, precomputed_residues, shift=0):
    """Run analysis for a specific targeted point."""
    print("\n" + "="*70)
    print(f"TARGETED POINT ANALYSIS: x = {TARGETED_X}")
    print("="*70)

    # x = r_m(m) - shift, so m = r_m(0) - shift - x  (r_m(m) = -m + r_m(0) here).
    # Omitting `- shift` used to check m=-9999 while the graph traced m=-10000.
    const = r_m(m=QQ(0)) - QQ(shift)
    target_m = QQ(-1) * TARGETED_X + const
    print(f"Target m-value: {target_m}")

    if not SYMBOLIC_SEARCH and precomputed_residues is not None:
        cov = compute_residue_coverage_for_m(target_m, precomputed_residues, prime_pool)
        print(f"\nPer-prime visibility: {len(cov['matched_primes'])}/{len(prime_pool)} primes matched ({cov['coverage_fraction']:.1%})")

        if cov['coverage_fraction'] > 0.5:
            print(f"\n✓ Target point has high visibility ({cov['coverage_fraction']:.1%})")
            print("It should have been found. Check rationality_test_func or height bounds.")
        elif cov['coverage_fraction'] > 0.1:
            print(f"\n⚠️  Target point has moderate visibility ({cov['coverage_fraction']:.1%})")
            print("May need larger prime subsets or more iterations.")
        else:
            print(f"\n✗ Target point has low visibility ({cov['coverage_fraction']:.1%})")
            print("Increase M_HEIGHT_BOUND or add more primes to pool.")

        sig = analyzer.visibility_signature(target_m)
        print(f"\nPer-prime visibility: {sig['matched']}/{sig['usable']} primes matched ({sig['fraction']:.1%})")

        if sig['fraction'] < 0.5:
            print("\n⚠️  TARGET POINT HAS LOW VISIBILITY")
            print(f"This point is only visible at {sig['fraction']:.1%} of usable primes.")
            print("\nMatched primes:", [p for p, (r, ok) in sig['per_prime'].items() if ok])
            print("Missing primes (sample):", [p for p, (r, ok) in sig['per_prime'].items() if not ok][:10])

            matched_primes = [p for p, (r, ok) in sig['per_prime'].items() if ok]
            if len(matched_primes) >= 4:
                suggested = matched_primes[:6]
                print(f"\nSuggested targeted subset: {suggested}")
                print("Add this to prime_subsets_to_process and re-run.")
        else:
            print(f"\n✓ Target point has high visibility ({sig['fraction']:.1%})")
            print("It should have been found. Check rationality_test_func or height bounds.")

@PROFILE
def print_search_summary(cumulative_stats, all_known_x):
    """Print summary of search results."""
    print("\n" + "="*70)
    print("SEARCH SUMMARY")
    print("="*70)
    print(f"Total points found: {len(all_known_x)}")
    print(f"Total time: {float(cumulative_stats.summary()['elapsed']):.1f}s")
    print(f"CRT candidates tested: {cumulative_stats.counters['crt_candidates_found']:,}")
    print(f"Rationality tests: {cumulative_stats.counters['rationality_tests_total']:,}")
    hit_rate = float(cumulative_stats.counters['rationality_tests_success']) / max(1, float(cumulative_stats.counters['rationality_tests_total']))
    print(f"Hit rate: {100*hit_rate:.2f}%")
    print("="*70)

@PROFILE
def run_sufficiency_proof_and_posterior(cumulative_stats, all_known_x, height_bound, current_sections, prime_pool, diag):
    """Run sufficiency proof and posterior probability analysis."""
    mw_rank = len(current_sections)

    def simple_height(x):
        q = QQ(x)
        num = abs(int(q.numerator()))
        den = abs(int(q.denominator()))
        return float(math.log(max(num, den, 1)))

    if all_known_x:
        h_obs_max = max(simple_height(x) for x in all_known_x)
        print(f"Proof using OBSERVED max height: {h_obs_max:.2f}")
    else:
        h_obs_max = height_bound
        print(f"Proof using SEARCH height: {h_obs_max:.2f}")

    # Prove the statement about the m box (M_HEIGHT_BOUND), not about the largest
    # point found so far: with only x=0 known the observed height is 0 and the old
    # check passed vacuously.
    run_sufficiency_proof(h_obs_max, cumulative_stats.prime_subsets, mw_rank,
                          m_height_bound=M_HEIGHT_BOUND)

    from stats import prior_from_arithmetic, completeness_posterior_geometric, bootstrap_visibility, FindabilityAnalyzer

    k_found = len(list(all_known_x))

    p_visibility = None
    if 'diag' in locals() and isinstance(diag, dict):
        p_visibility = float(diag['bootstrap']['avg_fraction'])

    if p_visibility is None:
        analyzer = FindabilityAnalyzer(cumulative_stats, prime_pool)
        quick_boot = bootstrap_visibility(analyzer, N_samples=2000, max_num=2000, max_den=2000, seed=42)
        p_visibility = float(quick_boot['avg_fraction'])
        print(f"[fallback bootstrap] avg_fraction (p) = {p_visibility:.4f}")

    selmer_dim = None
    r_found = None

    cnts = cumulative_stats.counters
    crt_candidates_found = cnts.get('crt_candidates_found', cnts.get('crt_candidates_tested', None))
    rationality_tests_success = cnts.get('rationality_tests_success', cnts.get('rationality_tests_total_success', None))

    h_max = None
    known_heights = None
    if all_known_x:
        known_heights = [simple_height(x) for x in all_known_x]
        h_max = max(known_heights) if known_heights else None

    rejected_primes_list = getattr(cumulative_stats, 'rejected_primes', [])

    prior = prior_from_arithmetic(
        k_found=k_found,
        p_visibility=p_visibility,
        rejected_primes=rejected_primes_list,
        prime_pool=prime_pool,
        selmer_dim=selmer_dim,
        r_found=r_found,
        crt_candidates_found=crt_candidates_found,
        rationality_tests_success=rationality_tests_success,
        h_max=h_max,
        known_heights=known_heights
    )

    print(f"\n--- Arithmetic-informed prior (with fiber collision adjustment) ---")
    if prior.get('collision_primes'):
        print(f"Fiber collision primes detected: {prior['collision_primes']}")
    print(f"p_visibility (raw): {prior['p_raw']:.4f}")
    print(f"p_visibility (adjusted): {prior['p_adjusted']:.4f}")
    print(f"mu_selmer:   {prior['mu_selmer']:.4g}")
    print(f"mu_local:    {prior['mu_local']:.4g}")
    print(f"mu_height:   {prior['mu_height']:.4g}")
    print(f"mu_bootstrap:{prior['mu_bootstrap']:.4g}")
    print(f"--> mu_combined = {prior['mu_combined']:.4g}  (q = {prior['q']:.6f})")

    m_max = 200
    post = completeness_posterior_geometric(k=k_found, p=prior['p_adjusted'], q=prior['q'], m_max=m_max)

    print("\n--- Posterior summary (geometric prior from arithmetic signals) ---")

    if 'P_all' not in post or 'P_all_but_1' not in post or 'P_all_but_2' not in post:
        print(f"Observed points (k) = {k_found}")
        print(f"Estimated detection probability p = {p_visibility:.3f}")
        print("⚠️  Could not compute posterior probabilities (p_visibility likely 0).")
        print("    Search may have been starved of valid primes.")
    else:
        P_all = post['P_all']
        P_all_but_1 = post['P_all_but_1']
        P_all_but_2 = post['P_all_but_2']
        mean_T = post['posterior_mean_T']

        print(f"Observed points (k) = {k_found}")
        print(f"Estimated detection probability p = {prior['p_adjusted']:.3f}")
        print(f"P(true T == k)         = {P_all:.3%}   (probability we found all points)")
        print(f"P(true T <= k+1)       = {P_all_but_1:.3%}   (probability we missed ≤ 1 point)")
        print(f"P(true T <= k+2)       = {P_all_but_2:.3%}   (probability we missed ≤ 2 points)")
        print(f"Posterior mean of T    = {mean_T:.3f}")
        print("Note: results depend on prior (mu_combined) computed from arithmetic signals above.\n")

        top_items = sorted(post['posterior'].items(), key=lambda t: -t[1])[:8]
        print("Top posterior mass (T, prob):", ", ".join([f"{int(T)}:{prob:.3%}" for T,prob in top_items]))

def validate_ramification_locus(cd, cumulative_stats):
    """Validate that detected fiber collisions match ramification locus."""
    ram_locus = compute_ramification_locus(cd)
    detected_collisions = set(p for p, r in cumulative_stats.rejected_primes if 'collision' in str(r))

    if USE_CONSENSUS_FILTER:
        print(f"\n✓ Fiber collisions detected across all geometries: {detected_collisions}")
        print(f"  Primary fibration ramification locus: {ram_locus}")
        print(f"  (Collisions may differ per fibration in consensus mode)")
    else:
        if not detected_collisions.issubset(ram_locus):
            print(f"\n⚠️  WARNING: Detected collisions {detected_collisions} not in ramification locus {ram_locus}")
        else:
            print(f"\n✓ Fiber collision detection validated: {detected_collisions} ⊆ ramification locus {ram_locus}")

def run_fibration_geometry_diagnostics(cd, current_sections, m_sym, singfibs):
    """Run automorphism and geometry diagnostics."""
    print("\n" + "="*70)
    print("FIBRATION GEOMETRY DIAGNOSTICS")
    print("="*70)

    print("\n--- Automorphism Search ---")
    if not current_sections:
        print("No sections found; skipping automorphism search preserving fibration.")
    else:
        auts_report = compute_auts_preserving_fibration(cd, current_sections, m_sym)
        scaling_autos = auts_report.get('scaling_autos', [])
        if scaling_autos:
            print(f"Found {len(scaling_autos)} scaling automorphisms:")
            for i, aut in enumerate(scaling_autos):
                print(f"  [{i}] Möbius map: (a,b,c,d) = {aut['mobius']}")
                print(f"      Scaling factor u = {aut['u']}")
        else:
            print("No scaling automorphisms found.")

        translation_autos = auts_report.get('translation_autos', [])
        if translation_autos:
            print(f"Found {len(translation_autos)} translation automorphisms:")
            for i, aut in enumerate(translation_autos):
                print(f"  [{i}] Translation by Section S{aut['section_index']}")
        else:
            print("No translation automorphisms found.")

    if not FINITE_FIELD:
        ns_auts, names = compute_ns_auts(singfibs, current_sections)
        if ns_auts:
            print(f"\nFound {len(ns_auts)} automorphisms of the NS lattice.")
            classified_ns_auts = classify_auts(ns_auts, names)
            print("Classified NS lattice automorphisms:")
            for i, (M, labels) in enumerate(classified_ns_auts):
                print(f"  [{i}] Matrix:\n{M}")
                print(f"      Labels: {labels}")
        else:
            print("\nNo non-trivial automorphisms found for the NS lattice.")

def run_torsion_analysis(cd, m_sym, base_sections):
    """Run torsion analysis on the fibration."""
    print("\n--- Torsion Analysis ---")
    if FINITE_FIELD:
        print("Torsion analysis over finite fields: Using specializations at field elements")
        specs = good_specializations(cd, m_sym, max_try=min(40, FINITE_FIELD // 2))
    else:
        specs = good_specializations(cd, m_sym, max_try=40)

    print("Got", len(specs), "good specializations for torsion check.")
    orders = []
    for m0, E in specs:
        if FINITE_FIELD:
            ab_grp = E.abelian_group()
            orders.append(ab_grp.order())
        else:
            tors = E.torsion_subgroup()
            orders.append(tors.order())

    if FINITE_FIELD:
        if orders:
            candidate_torsion_order = reduce(gcd, orders)
            print("GCD of specialized curve orders (informational only):", candidate_torsion_order)
        else:
            print("No valid specializations for torsion analysis")
    else:
        candidate_torsion_order = reduce(gcd, orders) if orders else 1
        print("Fast method candidate torsion order (GCD of specializations):", candidate_torsion_order)

    fiber_counts, lcm_bound = compute_fiber_lcm(cd)
    print("Fiber component counts:", fiber_counts, " -> lcm bound:", lcm_bound)

    for i, sec in enumerate(base_sections):
        is_torsion = False
        for n in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12]:
            if torsion_test(cd, sec, n, m_sym=m_sym, max_try=12):
                print(f"Base section {i} appears to be torsion of order dividing {n}.")
                is_torsion = True
                break
        if not is_torsion:
            print(f"Base section {i} does not appear to be small order torsion.")

def run_advanced_qq_diagnostics(cd, current_sections, prime_pool, singfibs, euler):
    """Run advanced diagnostics (saturation, Picard, Shioda-Tate, etc.) for QQ mode."""
    print("\n--- Saturation Diagnostics ---")
    run_saturation_checks(cd, current_sections, prime_pool[:30])

    print("\n--- Picard Analysis (Van Luijk) ---")
    ell_candidates = [p for p in prime_pool if p not in cd.bad_primes][:10]
    print(f"Using {len(ell_candidates)} good prime candidates for reduction: {ell_candidates}")

    picard_report = picard_via_van_luijk(
        cd,
        current_sections,
        prime_pool,
        ell_candidates=tuple(ell_candidates),
        verbose=True
    )
    print("\n=== Picard Report ===")
    print(f"Lower bound (char 0): {picard_report['lower_bound']}")
    print(f"Lower bounds on rho(S_ell) from reductions (NOT upper bounds on rho(S)):")
    for lb, info in picard_report['reduction_lower_bounds']:
        print(f"  ell={info['ell']}: rho(S_ell) >= {lb}    (rank_lb={info['rank_lb']}, Σ={info['sum_contrib']})")
    if picard_report['rho'] is not None:
        print(f"*** Picard number: ρ = {picard_report['rho']}  (rigorous: {picard_report.get('rho_rigorous')}; {picard_report.get('rho_method')}) ***")
    else:
        print("*** Picard number not determined: no rigorous upper bound available for chi >= 2. ***")

    print("\n--- Shioda-Tate Diagnostics ---")
    rank_guess, details, diag = shioda_tate_from_fiber_list(
        singfibs['fibers'],
        rho_geom=picard_report['rho'],
        return_diagnostics=True,
        allow_auto_rho=True
    )

    if rank_guess is None:
        print(f"Rank could not be determined. Reason: {diag.get('note', 'Unknown')}")
    else:
        print(f"Shioda-Tate Rank Estimate (assuming rho={picard_report['rho']}): {rank_guess}")

    print(f"Total Euler Characteristic: {euler}")
    print(f"Sum of Fiber Contributions (Σ(m_v - 1)): {details['sum_contributions']}")

    compute_selmer_rank_bounds(cd, rank_guess, verbose=True)
    print("")

    _, chi = compute_euler_and_chi(cd)
    if picard_report['rho'] is not None and chi != 1 and False:
        run_rational_curve_analysis(cd, current_sections, picard_report['rho'], rank_guess, chi)

def run_rational_curve_analysis(cd, current_sections, rho, rank_guess, chi):
    """Run Yau-Zaslow rational curve counting analysis."""
    print("\n--- Rational Curve Counts (Yau-Zaslow) ---")
    print("running with rho, mw rank, chi =", rho, rank_guess, chi)

    basis_labels, Q, h_vec = build_ns_basis_and_Q(cd, rho, mw_rank=rank_guess, chi=chi)

    mcoords = tuple(range(11, 75))
    counts, reps = staged_rational_curve_search(
        cd,
        current_sections,
        rho, rank_guess, chi,
        height_bounds=(15, 25, 35, 45, 55),
        max_coords=mcoords,
        node_cap=15_000_000,
        return_reps=True,
        require_S_coeff='positive',
        targeted_fallback=True
    )

    runs = run_convergence_test(cd, current_sections, rho, chi, rank_guess,
                                max_coords_seq=(20, 24, 28, 31), require_S_coeff='positive')

    print(f"Found rational curve classes in {len(counts)} different degrees.")
    print("Counts per degree:", counts)

    print("\nSample representatives (first few degrees):")
    for d in sorted(reps.keys())[:6]:
        print(f"\nDegree {d}, count {counts.get(d, 0)}:")
        for v in reps[d][:8]:
            print("   ", decode_vector(v, basis_labels))

    if current_sections:
        comp_map = detect_section_component(cd, current_sections[0])
        print("\nSection-component intersection map (heuristic):", comp_map)

    qseries = build_qseries_from_counts(counts, rho, max_degree=20)
    print("\nQ-series (up to q^12):", qseries)

    cands = find_isotropic_fibration_candidates(cd, current_sections, rho, rank_guess, chi)
    results = evaluate_fibration_height_reduction(cd, current_sections, rho, rank_guess, chi, candidates=cands, shioda_sign=-1)

    if results:
        top = results[0]
        print("best coeffs:", top['a'])
        print("old heights:", top['heights_old'])
        print("new heights:", top['heights_new'])
        print("per-section delta (old-new):", top['delta'])
        print("total reduction:", top['total_reduction'])
    else:
        print("no isotropic candidates found in box")

@PROFILE
# =============================================================================
# doloop_genus2: one fibration
# =============================================================================

@_dc.dataclass
class FibrationSetup:
    """Everything doloop_genus2 derives from (data_pts, sextic_coeffs) before searching."""
    field_data: dict
    base_pts: list
    shifted_G_poly: object
    T: object
    T_inv: object
    all_known_x: set          # NB: apply_mobius_transformation may hand back a different set object
    primary_tower: list
    fibrations: object
    tower_for_mumford: object
    r_m: object
    cd: object
    sconf: dict
    prime_pool: list
    search_rhs_list: list
    testfunc: object
    shift: object


def _build_fibration_setup(data_pts, sextic_coeffs, all_known_x):
    """Field/ring setup -> shift & Mobius transforms -> tower -> curve data -> search configuration."""
    if FINITE_FIELD and MOBIUS_TRANS:
        raise RuntimeError("Mobius transforms are disabled in finite-field mode")

    field_data = setup_field_and_rings(sextic_coeffs, data_pts)
    base_field = field_data['base_field']

    shifted_G_poly, base_pts, shift = apply_shift_transformation(
        field_data['G'], field_data['real_pts'], base_field
    )
    shifted_G_poly, base_pts, T, T_inv, all_known_x = apply_mobius_transformation(
        shifted_G_poly, all_known_x, base_pts
    )

    primary_tower, fibrations, tower_for_mumford = build_tower_and_fibrations(
        shifted_G_poly, base_pts
    )

    E_rhs_m, r_m, roots = extract_geometry_from_tower(primary_tower, field_data['Fm'])
    cd, morphism_data = build_curve_data(E_rhs_m, roots, base_pts)
    one, two, three = morphism_data

    sconf, prime_pool = configure_search_parameters(cd, all_known_x, base_pts, base_field)

    E_rhs_m_symbolic = primary_tower[-1]['f_i'] if not FINITE_FIELD else None
    search_rhs_list = build_search_rhs_list(cd, roots, E_rhs_m_symbolic, one, two, three)

    testfunc, shift = setup_rationality_test_function(shift, T, T_inv)

    return FibrationSetup(
        field_data=field_data, base_pts=base_pts, shifted_G_poly=shifted_G_poly,
        T=T, T_inv=T_inv, all_known_x=all_known_x, primary_tower=primary_tower,
        fibrations=fibrations, tower_for_mumford=tower_for_mumford, r_m=r_m, cd=cd,
        sconf=sconf, prime_pool=prime_pool, search_rhs_list=search_rhs_list,
        testfunc=testfunc, shift=shift,
    )


def _compute_initial_sections(setup, data_pts):
    """
    Fibration diagnostics, special-fiber scan, base Mordell-Weil sections
    (LLL-reduced).  Returns (base_sections, singfibs, euler), or None if no
    base sections could be computed.
    """
    cd, base_pts = setup.cd, setup.base_pts

    summarize_fibration_info(cd, data_pts, base_pts)

    extra_pts = scancd_for_special_fibers(cd, setup.r_m, setup.shift)
    if extra_pts:
        setup.all_known_x.update(extra_pts)

    singfibs = cd.singfibs
    euler = singfibs['euler_characteristic']

    base_sections = compute_base_sections_m(cd, base_pts, tower=setup.primary_tower)
    verify_morphism_on_samples(cd, base_pts)

    if not base_sections:
        print("Could not compute base sections. Skipping search.")
        return None

    return lll_reduce_mw_basis(cd, base_sections), singfibs, euler


def _independence_and_height_matrix(current_sections, cd):
    """
    (independent, H) for the current sections.  H is the Shioda-Tate height
    pairing matrix; forced to [[1]] in finite-field mode.
    """
    independent, H = check_independence(current_sections, cd.E_weier, cd)
    if FINITE_FIELD:
        H = Matrix([QQ(1)])
    if not independent:
        return False, H

    # check_independence intentionally returns H=None for a single section
    # (nothing to test independence against). That's still a valid 1x1
    # height-pairing matrix <P,P> for downstream consumers -- compute it
    # explicitly rather than letting None reach assess_curve_difficulty.
    if H is None:
        if len(current_sections) != 1:
            raise RuntimeError(
                f"check_independence returned H=None for {len(current_sections)} "
                f"sections; None is only expected for the n==1 case."
            )
        H = compute_canonical_height_matrix(current_sections, cd) if USE_MINIMAL_MODEL \
            else compute_coarse_height_matrix_serializable(cd, current_sections)
        if H is None or H.nrows() != 1:
            raise RuntimeError(
                "Failed to compute 1x1 height matrix for the single current section."
            )
    return True, H


def _apply_difficulty_to_height_bound(cd, current_sections, prime_pool, H, height_bound):
    """QQ mode: widen the height bound if the curve is predicted to be difficult."""
    predictor = CurveComplexityPredictor()
    difficulty = predictor.assess_curve_difficulty(cd, current_sections, prime_pool, H)

    if difficulty['difficulty_score'] > 2.0:
        print(f"⚠️  WARNING: Curve predicted to be difficult (score {difficulty['difficulty_score']:.2f})")
        height_bound *= difficulty['recommended_height_multiplier']
    return height_bound


def _print_height_bound_certification(H, current_sections, vecs, height_bound):
    """
    Rank-1 only: vecs are the enumerated multiplier vectors (n,) after
    compute_search_vectors + canonicalize_by_sign. The largest n actually
    enumerated is the one unambiguous, code-verified fact about "how far out
    did this run search" -- no formula translating it into a canonical- or
    naive-height number is included, because doing that correctly requires
    matching Sage's QuadraticForm.short_vector_list_up_to_length scaling
    exactly, which was not independently verified when this print was added.
    Trust n_max itself, not any derived height estimate; the ACTUAL naive
    x-height of every point found is printed as it's found (search for
    "[height]" in the log), which is ground truth rather than a formula.
    """
    try:
        if H.nrows() == 1 and len(current_sections) == 1:
            n_values = [abs(int(v[0])) for v in vecs if len(v) == 1]
            n_max = max(n_values) if n_values else 0
            print(f"[height-bound certification] HEIGHT_BOUND={height_bound} -> enumerating "
                  f"multiples of the base section P up to n = ±{n_max} this iteration "
                  f"({len(vecs)} distinct multiplier(s) after sign-canonicalization). "
                  f"See per-point '[height]' lines below for the actual naive x-height reached "
                  f"by each candidate found at these multiples.")
        else:
            print(f"[height-bound certification] Skipped: rank != 1 ({H.nrows()} sections) -- "
                  f"'height_bound' does not correspond to a single multiplier in this case.")
    except Exception as e:
        print(f"[height-bound certification] Could not compute: {e}")


def _run_search_pass(setup, current_sections, sextic_coeffs, cumulative_stats, height_bound, iteration=0):
    """
    One pass of the section-search loop: independence check, height matrix,
    search vectors, then run_single_search_iteration.

    Returns (newly_found_transformed_x, height_bound); the set is empty if the
    pass stopped early (no sections / dependent sections / no vectors).

    NOTE: this used to be a `while True:` loop, but an unconditional `break`
    after the first pass made everything below it unreachable -- "if not
    new_sections: break", augmenting current_sections with the new sections
    (already commented out: `#current_sections.extend(new_sections)`), then
    lll_reduce_mw_basis and iteration += 1.  Multi-iteration augmentation is
    therefore currently disabled; the loop is a single pass.  That dead tail
    was removed here rather than kept as unreachable code.
    """
    cd, prime_pool = setup.cd, setup.prime_pool
    all_known_x = setup.all_known_x

    print(f"\n--- Search Iteration {iteration} with {len(current_sections)} sections ---")

    if not current_sections:
        print("No independent sections to search with. Stopping.")
        return set(), height_bound

    independent, H = _independence_and_height_matrix(current_sections, cd)
    if not independent:
        print("Warning: Section basis is linearly dependent. Stopping search.")
        return set(), height_bound

    print("Height Pairing Matrix H:\n", H)

    if not FINITE_FIELD:
        height_bound = _apply_difficulty_to_height_bound(cd, current_sections, prime_pool, H, height_bound)

    if FINITE_FIELD:
        vecs = generate_ff_search_vectors(len(current_sections))
    else:
        vecs = compute_search_vectors(H, height_bound)

    vecs = canonicalize_by_sign(vecs)
    print(f"Searching {len(vecs)} vectors up to height {height_bound}...")

    if not FINITE_FIELD:
        _print_height_bound_certification(H, current_sections, vecs, height_bound)

    if not vecs:
        print("No search vectors found within height bound. Stopping.")
        return set(), height_bound

    base_pts = setup.base_pts
    # x_b: base point x-coord in the shifted system (GF(p) element in FF mode)
    x_b_for_aug = base_pts[0][0] if base_pts else None
    # shifted_coeffs: coefficients of shifted_G_poly for fiber augment
    shifted_coeffs_for_aug = list(setup.shifted_G_poly.list())

    # height_pairing_H is the Shioda-Tate matrix computed above, passed straight
    # through to the per-vector height filter so search_lll._resolve_height_bound
    # doesn't try to recompute it via E.height_pairing_matrix() -- which doesn't
    # exist on cd.E_weier (an elliptic curve over the function field
    # Frac(QQ[m]), not over QQ/a number field), so that path always threw and
    # silently fell back to the flat HEIGHT_BOUND.  H already matches
    # current_sections' ordering (compute_search_vectors(H, ...) built `vecs`
    # from it), so this passes through a value that exists rather than deriving one.
    newly_found_x, new_sections, iter_stats = run_single_search_iteration(
        cd, current_sections, cd.E_weier, height_bound, prime_pool, setup.sconf,
        vecs, setup.search_rhs_list, setup.r_m, setup.shift, all_known_x, setup.testfunc,
        setup.tower_for_mumford, sextic_coeffs, setup.fibrations, base_pts, setup.primary_tower,
        x_b=x_b_for_aug, shifted_coeffs=shifted_coeffs_for_aug,
        height_pairing_H=H,
    )

    cumulative_stats.merge(iter_stats)

    print(f"Found {len(newly_found_x)} new point(s) and {len(new_sections)} new section(s).")
    if newly_found_x and not FINITE_FIELD:
        print(f"New x-coordinates: {newly_found_x}")

    all_known_x.update(newly_found_x)
    # (The old `if len(all_known_x) >= TERMINATE_WHEN_6 and not FINITE_FIELD: break`
    #  sat immediately before an unconditional `break`, so it never mattered.)

    return set(newly_found_x), height_bound


def _run_post_search_diagnostics(setup, cumulative_stats, height_bound, current_sections,
                                 base_sections, singfibs, euler):
    cd, prime_pool = setup.cd, setup.prime_pool

    if not FINITE_FIELD:
        # precomputed_residues=None on purpose (preserving historical behavior): this used to
        # be `locals().get('precomputed_residues')`, which was always None because the residues
        # computed inside run_single_search_iteration are never returned to the caller.  As a
        # result run_targeted_point_analysis silently skips its residue-coverage section.
        run_qq_mode_diagnostics(cumulative_stats, prime_pool, height_bound, setup.all_known_x,
                                setup.r_m, setup.shift, setup.field_data['real_pts'], setup.base_pts,
                                setup.T, current_sections, cd, precomputed_residues=None)

    # Fibration geometry diagnostics (both modes)
    run_fibration_geometry_diagnostics(cd, current_sections, cd.a4.parent().gen(), singfibs)
    run_torsion_analysis(cd, cd.a4.parent().gen(), base_sections)

    if not FINITE_FIELD:
        run_advanced_qq_diagnostics(cd, current_sections, prime_pool, singfibs, euler)


def _map_points_to_original_coords(transformed_x, T_inv):
    """Undo the Mobius transform on newly found x's (QQ mode only)."""
    if T_inv and not FINITE_FIELD:
        points = set(apply_to_points(transformed_x, T_inv))
        if transformed_x:
            print(f"Transformed {len(transformed_x)} new points back to original geometry.")
        return points
    return transformed_x


def doloop_genus2(data_pts, sextic_coeffs, all_known_x, cumulative_stats):
    """
    Search one fibration built from data_pts.

    Two modes:
    - QQ mode (FINITE_FIELD=None): Search for rational points
    - Finite field mode (FINITE_FIELD=p): Solve HECC DLP via index calculus

    Returns:
        - QQ mode: (set of new x-coordinates, updated stats)
        - FF mode: (set containing factor base x-coords, updated stats)
    """
    setup = _build_fibration_setup(data_pts, sextic_coeffs, all_known_x)

    initial = _compute_initial_sections(setup, data_pts)
    if initial is None:
        return set(), cumulative_stats
    base_sections, singfibs, euler = initial
    current_sections = list(set(base_sections))

    all_newly_found_transformed_x, height_bound = _run_search_pass(
        setup, current_sections, sextic_coeffs, cumulative_stats, HEIGHT_BOUND)

    _run_post_search_diagnostics(setup, cumulative_stats, height_bound, current_sections,
                                 base_sections, singfibs, euler)

    return _map_points_to_original_coords(all_newly_found_transformed_x, setup.T_inv), cumulative_stats

if globals().get("__name__", None) == "__main__":
    main_genus2()
