/* generated by picard_pointcount_pipeline.py */
/* Keep per-thread stack usage sane on 32-64 thread machines.
   PARI documents that thread stacks multiply with nbthreads. */
default(parisize, 512M);
default(parisizemax, 8G);
default(threadsizemax, 512M);

p = 47;
chi = 2;
maxk = 6;
a4c = [42,0,27,0,40,0,39,0,43];
a6c = [44,0,30,0,12,0,44,0,2,0,26,0,35];
a4d = Mod(1, p);
a6d = Mod(1, p);
a4inf = Mod(43, p);
a6inf = Mod(35, p);
outfile = "picard_pointcounts/p47.out";

eval_poly(c,t) =
{
  my(s=0,i);
  for(i=1,#c, s += Mod(c[i],p)*t^(i-1));
  s
};

a4eval(t) = eval_poly(a4c,t) / a4d;
a6eval(t) = eval_poly(a6c,t) / a6d;

qchar(z,q) =
{
  if(z == 0, return(0));
  if(z^((q-1)\2) == 1, 1, -1)
};

canonical_coeffs(c,d) =
{
  my(nc=vector(d,i,i));
  for(i=1,d,
    if(mod((i-1)-d,2) == 0,
      nc[i]=c[i],
      nc[i]=if(c[i]==0,0,p-c[i])
    )
  );
  nc
};

lexle(a,b,d) =
{
  my(i);
  for(i=1,d,
    if(a[i] < b[i], return(1));
    if(a[i] > b[i], return(0));
  );
  1
};

trace_fibre(t,d) =
{
  my(a, r, pm1, A=a4eval(t), B=a6eval(t), D=4*A^3+27*B^2, q=p^d,
     tr=vector(maxk\d, rr, 0), pm2=2);

  if(D == 0,
    my(c6=-864*B, sg=qchar(-c6,q));
    if(sg == 0, error("singular fibre with c6=0: additive reduction not supported"));
    for(r=1,floor(maxk\d), tr[r]=sg^r),
    my(E=ellinit([A,B]));
    a=ellap(E);
    if(d==1,
      print("TRACE_DEBUG t=", t, " A4=", A, " A6=", B, " ellap=", a)
    );
    pm1=a;
    for(r=1,floor(maxk\d),
      if(r==1,
        tr[r]=a,
        tr[r]=a*pm1-q*pm2
      );
      if(r==1, pm2=2; pm1=a, pm2=pm1; pm1=tr[r])
    )
  );
  tr
};

process_range(spec) =
{
  my(lo=spec[1], hi=spec[2], d=spec[3], c=vector(d), nc,
     prefix, z, j, cc, f, elt, tr, weight, full_count=0,
     irr_count=0, rep_count=0, fixed_count=0,
     acc=vector(floor(maxk\d), rr, 0));

  for(prefix=lo,hi,
    z=prefix;
    for(j=2,d,
      c[j]=z%p;
      z=floor(z/p)
    );
    for(cc=0,p-1,
      c[1]=cc;
      f='x^d;
      for(j=1,d, f += Mod(c[j],p)*'x^(j-1));
      nc=canonical_coeffs(c,d);
      if(lexle(c,nc,d),
        if(polisirreducible(f),
          irr_count++;
          rep_count++;
          weight=if(c==nc,1,2);
          if(weight==1, fixed_count++);
          full_count += weight;
          if(d==1,
            elt=Mod(-c[1],p),
            elt=ffgen(f)
          );
          tr=trace_fibre(elt,d);
          for(j=1,#acc, acc[j] += weight*d*tr[j])
        )
      )
    )
  );
  [acc, full_count, irr_count, rep_count, fixed_count]
};

exportall();

A = vector(maxk, k, 0);
degree_full_counts = vector(maxk, k, 0);
degree_rep_counts = vector(maxk, k, 0);

/* The point at infinity on the base is a single degree-1 place. */
trace_infinity() =
{
  my(a, r, A=a4inf, B=a6inf, D=4*A^3+27*B^2, tr=vector(maxk), q=p);
  if(D == 0,
    my(sg=qchar(-864*B,q));
    if(sg == 0, error("infinity has additive reduction"));
    for(r=1,maxk, tr[r]=sg^r),
    /* Smooth fiber at infinity */
    my(E=ellinit([A,B]));
    a=ellap(E);
    if(maxk>=1, tr[1]=a);
    for(r=2,maxk, tr[r]=a*tr[r-1]-q*if(r==2,2,tr[r-2]))
  );
  tr
};

inftr = trace_infinity();
for(k=1,maxk, A[k] += inftr[k]);

for(d=1,maxk,
  if(d > maxk, break);
  pref_total = p^(d-1);
  chunk_size = ceil(pref_total / 64);
  if(chunk_size < 1, chunk_size=1);
  chunks = [];
  forstep(lo=0,pref_total-1,chunk_size,
    hi=min(pref_total-1,lo+chunk_size-1);
    chunks=concat(chunks, [[lo,hi,d]])
  );
  export(chunks);
  t0=getabstime();
  pieces=parvector(#chunks,i,process_range(chunks[i]));
  degree_sum=vector(floor(maxk\d),rr,0);
  deg_full=0; deg_irr=0; deg_rep=0; deg_fixed=0;
  for(i=1,#pieces,
    for(j=1,#degree_sum, degree_sum[j]+=pieces[i][1][j]);
    deg_full += pieces[i][2];
    deg_irr += pieces[i][3];
    deg_rep += pieces[i][4];
    deg_fixed += pieces[i][5]
  );
  expected=ffnbirred(p,d);
  if(deg_full != expected,
     error(Str("degree ",d," closed point count mismatch: ",deg_full," != ",expected))
  );
  for(r=1,#degree_sum, A[d*r] += degree_sum[r]);
  degree_full_counts[d]=deg_full;
  degree_rep_counts[d]=deg_rep;
  write(outfile,
        "DEGREE ",d,
        " FULL_CLOSED ",deg_full,
        " REPS ",deg_rep,
        " IRR_CANDIDATES ",deg_irr,
        " INV_FIXED ",deg_fixed,
        " SECONDS ",getabstime()-t0);
  write(outfile, "DEGREE_TRACE ",d," ",degree_sum);
);

/* Convert the sum of fibre traces into the H^2/twist power sums.
   #S(F_q^k) = (q^k+1)^2 - A_k.
   Tr(H^2) = #S - 1 - q^(2k) = 2q^k - A_k.
   The twist trace is Tr(H^2) - 10 q^k = -A_k - 8q^k. */
chi_shift = 10 * 2 - 2
twist = vector(maxk,k,-A[k]-chi_shift*p^k);
surface_counts = vector(maxk,k,(p^k+1)^2-A[k]);
h2 = vector(maxk,k,2*p^k-A[k]);
chi_sum = vector(maxk,k,-A[k]);

write(outfile,"PRIME ",p);
write(outfile,"MODEL_CHI ",chi);
write(outfile,"A_FIBRE_TRACES ",A);
write(outfile,"CHI_SUMS ",chi_sum);
write(outfile,"SURFACE_COUNTS ",surface_counts);
write(outfile,"H2_TRACES ",h2);
write(outfile,"TWIST_POWER_SUMS ",twist);
write(outfile,"END");
quit();
